---
title: "Adult_5.40.5_DissertationCode"
author: "Brian Joseph"
date: "2025-01-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Intall_and_load_necessary_packages}

#install.packages('TDAmapper')
library(TDAmapper)
library(cluster)
library(vip)
#install.packages('kernlab’)
library(kernlab)
#install.packages(‘class’)
library(class)
#install.packages('nnet')
library(nnet)
#install.packages(‘randomForest’)
library(randomForest)
#install.packages('e1071')
library(e1071)                                                  
#install.packages("BayesFactor")
library(BayesFactor)
library(BayesPPD)
library(bayestestR)
#install.packages('igraph')
library('igraph')
#install.packages('locfit')
library(locfit)
#install.packages('ggplot2’)
library(ggplot2)
library(dplyr)
#install.packages('networkD3')
library(networkD3)
library(rstanarm)
library(see)
#install.packages('tidyverse')
library(tidyverse)
#install.packages('caret')
library(caret)
#install.packages('ISLR')
library(ISLR)
#install.packages('MCMCpack')
library(MCMCpack)
#linstall.packages("caret")
library(caret)
library(TDA)
library(TDAstats)
library(ks)
#install.packages('MLmetrics')
library(MLmetrics)
#install.packages('googledrive')
library(googledrive)
#install.packages('stringr')
library(stringr)
#install.packages('ks')
library(ks)
library(GGally)

```



```{r importDatasetsFromFilesOnHardDrive}
#import adult dataset from UCI repository stored on my desktop

#Adult **
adult <- read.csv("~/Desktop/NCU/DissertationDatasets/Adult/adult.data", header=FALSE)
  head(str(adult))
  summary(adult)
  ggpairs(adult[,c(1,3,5,11,12,13,15)])

  
 
```


```{r AddBayesianTestFuntions}

##Add Bayesian tests functions

#create function to conduct the Bayesian Sign Test
BayesianSignTest <- function(diffVector,rope_min,rope_max) {

  library(MCMCpack)

  samples <- 3000

  #build the vector 0.5 1 1 ....... 1 

  weights <- c(0.5,rep(1,length(diffVector)))

  #add the fake first observation in 0

  diffVector <- c (0, diffVector)  


  #for the moment we implement the sign test. Signedrank will follows

  probLeft <- mean (diffVector < rope_min)

  probRope <- mean (diffVector > rope_min & diffVector < rope_max)

  probRight <- mean (diffVector > rope_max)

  results = list ("probLeft"=probLeft, "probRope"=probRope,
                  
                  "probRight"=probRight)
  
  return (results)
}


##Create function to conduct Bayesian Signed Rank Test

BayesianSignedRank <- function(diffVector,rope_min,rope_max) {
  
  library(MCMCpack)
  
  samples <- 30000
  
  #build the vector 0.5 1 1 ....... 1
  weights <- c(0.5,rep(1,length(diffVector)))
  
  #add the fake first observation in 0
  diffVector <- c (0, diffVector)
  
  sampledWeights <- rdirichlet(samples,weights)
  
  winLeft <- vector(length = samples)
  winRope <- vector(length = samples)
  winRight <- vector(length = samples)
  
  for (rep in 1:samples){
    currentWeights <- sampledWeights[rep,]
    for (i in 1:length(currentWeights)){
      for (j in 1:length(currentWeights)){
        product= currentWeights[i] * currentWeights[j]
        if (diffVector[i]+diffVector[j] > (2*rope_max) ) {
          winRight[rep] <- winRight[rep] + product
        }
        else if (diffVector[i]+diffVector[j] > (2*rope_min) ) {
          winRope[rep] <- winRope[rep] + product
        }
        else {
          winLeft[rep] <- winLeft[rep] + product
        }

      }
    }
    maxWins=max(winRight[rep],winRope[rep],winLeft[rep])
    winners = (winRight[rep]==maxWins)*1 + (winRope[rep]==maxWins)*1 + (winLeft[rep]==maxWins)*1
    winRight[rep] <- (winRight[rep]==maxWins)*1/winners
    winRope[rep] <- (winRope[rep]==maxWins)*1/winners
    winLeft[rep] <- (winLeft[rep]==maxWins)*1/winners
  }
  
  
  results = list ("winLeft"=mean(winLeft), "winRope"=mean(winRope),
                  "winRight"=mean(winRight) )
  return (results)
  
}


#Create function to conduct the Bayesian Correlated t.test

#diff_a_b is a vector of differences between the two classifiers, on each fold of cross-validation.
#If you have done 10 runs of 10-folds cross-validation, you have 100 results for each classifier.
#You should have run cross-validation on the same folds for the two classifiers.
#Then diff_a_b is the difference fold-by-fold.

#rho is the correlation of the cross-validation results: 1/(number of folds)
#rope_min and rope_max are the lower and the upper bound of the rope
 
correlatedBayesianTtest <- function(diff_a_b,rho,rope_min,rope_max){
   if (rope_max < rope_min){
     stop("rope_max should be larger than rope_min")
   }
     
  delta <- mean(diff_a_b)
  n <- length(diff_a_b)
  df <- n-1
  stdX <- sd(diff_a_b)
  sp <- sd(diff_a_b)*sqrt(1/n + rho/(1-rho))
  p.left <- pt((rope_min - delta)/sp, df)
  p.rope <- pt((rope_max - delta)/sp, df)-p.left
  results <- list('left'=p.left,'rope'=p.rope,'right'=1-p.left-p.rope)
  return (results)
}

```

```{r Set_Seed_for_reproducible_results}

set.seed(16974)

```

```{r Onehot_encoding_if_necessary_for_Persistent_Homology, cache=TRUE}

###Prepare datasets for One hot encoding if necessary and Persistent homology of each dataset.
##One hot encoding for adult dataset
library(caret)

#define one-hot encoding function
dummy.adult <- dummyVars(" ~ .", data=adult)

#perform one-hot encoding on data frame
adult.one_hot_df <- data.frame(predict(dummy.adult, newdata=adult))


#str final data frame
head(str(adult.one_hot_df))
adult_df1<-adult[,15]
adult.one_hot_df1<-cbind(adult.one_hot_df,adult_df1)
adult.one_hot_df2<-adult.one_hot_df1[,c(1,11,28,64,65,66)]

##Persistent homology of adult dataset

#create a random sample of adult.one_hot dataset to see if a barcode and persistent diagram can resolve from size of the dataset. 

adult.one_hot_1000_df <- adult.one_hot_df[sample(nrow(adult.one_hot_df), size = 1000, replace = FALSE), ]
head(str(adult.one_hot_1000_df))
summary(adult.one_hot_1000_df)


# calculate persistent homology for adult.one_hot_1000_df
phom.adult.one_hot_1000_df <- calculate_homology(adult.one_hot_1000_df)

# plot barcode for adult.one_hot_1000_df
plot_barcode(phom.adult.one_hot_1000_df)

# plot persistent diagram of adult.one_hot_1000_df dataset
plot_persist(phom.adult.one_hot_1000_df)



```

```{r Mapper Algorithm on Datasets, cache=TRUE}
#####———————————————MAPPER ALGORITHM————————————————

#Prepare Adult dataset for Mapper 1D algorithm
adult_df1<-adult[,15]
adult.one_hot_df1<-cbind(adult.one_hot_df,adult_df1)
adult.one_hot_df2<-adult.one_hot_df1[,c(1,11,28,64,65,66,109)]
adult.one_hot_df3<-adult.one_hot_df1[,c(1,11,28,62,63,64,65,66)]
adult.one_hot_df4<-adult.one_hot_df1[,-c(109,110)] 

##Two Filter Functions PCA & KDE

#Prepare linear PCA as a filter function by centering and scaling dataset first on all one hot df dataset
b<- prcomp(adult.one_hot_df, center=TRUE, scale=TRUE)
ts_pca_b <- as.data.frame(predict(b, adult.one_hot_df))

#Conduct kernel density estimator as a filter function on 4 of 6
filter.kde <- kde(adult.one_hot_df3[,1:4],H=diag(1,nrow = 4),eval.points =adult.one_hot_df3[,1:4])$estimate




##*** Adult Mapper 5 intervals, 40% overlap, 5 bins

m_adult_5.40.5 <- mapper1D(
     distance_matrix = dist(adult.one_hot_df),
     filter_values = c(ts_pca_b$PC1),
     num_intervals = 5,
     percent_overlap = 40,
     num_bins_when_clustering = 5)


g_adult_5.40.5 <- graph.adjacency(m_adult_5.40.5$adjacency, mode="undirected")
plot(g_adult_5.40.5, layout = layout.auto(g_adult_5.40.5))


head(str(m_adult_5.40.5$level_of_vertex))

head(str(m_adult_5.40.5$vertices_in_level))

head(str(m_adult_5.40.5$points_in_vertex))



my_resolution = 100
my_palette = colorRampPalette(c('red','green','lightblue'))
my_max = max(m_adult_5.40.5$level_of_vertex, na.rm=TRUE)
my_vector = m_adult_5.40.5$level_of_vertex / my_max

my_colors = my_palette(my_resolution)[as.numeric(cut(
                       my_vector, breaks=my_resolution))]

g_adult_5.40.5 <- graph.adjacency(m_adult_5.40.5$adjacency, mode="undirected")
vertex_size <- unlist(lapply(m_adult_5.40.5$points_in_vertex,
                             function(x) length(x)))

plot(g_adult_5.40.5, layout = layout.auto(g_adult_5.40.5),
     vertex.size = 30*log(vertex_size)/
     max(log(vertex_size)),
     vertex.color = my_colors)

m_adult_5.40.5.n1<-m_adult_5.40.5$points_in_vertex[1]
	m_adult_5.40.5.n1.vec<-as.vector(unlist(m_adult_5.40.5.n1))
m_adult_5.40.5.n2<-m_adult_5.40.5$points_in_vertex[2]
	m_adult_5.40.5.n2.vec<-as.vector(unlist(m_adult_5.40.5.n2)) 
m_adult_5.40.5.n3<-m_adult_5.40.5$points_in_vertex[3]
	m_adult_5.40.5.n3.vec<-as.vector(unlist(m_adult_5.40.5.n3))
m_adult_5.40.5.n4<-m_adult_5.40.5$points_in_vertex[4]
	m_adult_5.40.5.n4.vec<-as.vector(unlist(m_adult_5.40.5.n4)) 
m_adult_5.40.5.n5<-m_adult_5.40.5$points_in_vertex[5]
	m_adult_5.40.5.n5.vec<-as.vector(unlist(m_adult_5.40.5.n5))

##map the ID’s of each Mapper vertex point to the actual Adult One Hot DF1 dataset
tda.m_adult_5.40.5.n1.vec<-adult.one_hot_df4[m_adult_5.40.5.n1.vec,]
tda.m_adult_5.40.5.n2.vec<-adult.one_hot_df4[m_adult_5.40.5.n2.vec,]
tda.m_adult_5.40.5.n3.vec<-adult.one_hot_df4[m_adult_5.40.5.n3.vec,]
tda.m_adult_5.40.5.n4.vec<-adult.one_hot_df4[m_adult_5.40.5.n4.vec,]
tda.m_adult_5.40.5.n5.vec<-adult.one_hot_df4[m_adult_5.40.5.n5.vec,]


##*** Adult Mapper KDE 5 intervals, 40% overlap, 5 bins

m_kde_adult_5.40.5 <- mapper1D(
     distance_matrix = dist(adult.one_hot_df),
     filter_values = c(filter.kde),
     num_intervals = 5,
     percent_overlap = 40,
     num_bins_when_clustering = 5)


g_kde_adult_5.40.5 <- graph.adjacency(m_kde_adult_5.40.5$adjacency, mode="undirected")
plot(g_kde_adult_5.40.5, layout = layout.auto(g_kde_adult_5.40.5))


head(str(m_kde_adult_5.40.5$level_of_vertex))

head(str(m_kde_adult_5.40.5$vertices_in_level))

head(str(m_kde_adult_5.40.5$points_in_vertex))



my_resolution = 100
my_palette = colorRampPalette(c('red','green','lightblue'))
my_max = max(m_kde_adult_5.40.5$level_of_vertex, na.rm=TRUE)
my_vector = m_kde_adult_5.40.5$level_of_vertex / my_max

my_colors = my_palette(my_resolution)[as.numeric(cut(
                       my_vector, breaks=my_resolution))]

g_kde_adult_5.40.5 <- graph.adjacency(m_kde_adult_5.40.5$adjacency, mode="undirected")
vertex_size <- unlist(lapply(m_kde_adult_5.40.5$points_in_vertex,
                             function(x) length(x)))

plot(g_kde_adult_5.40.5, layout = layout.auto(g_kde_adult_5.40.5),
     vertex.size = 30*log(vertex_size)/
     max(log(vertex_size)),
     vertex.color = my_colors)



##Extract the ID observations of each mapper output vertex
m_kde_adult_5.40.5.n1<-m_kde_adult_5.40.5$points_in_vertex[1]
	m_kde_adult_5.40.5.n1.vec<-as.vector(unlist(m_kde_adult_5.40.5.n1))
m_kde_adult_5.40.5.n2<-m_kde_adult_5.40.5$points_in_vertex[2]
	m_kde_adult_5.40.5.n2.vec<-as.vector(unlist(m_kde_adult_5.40.5.n2)) 
m_kde_adult_5.40.5.n3<-m_kde_adult_5.40.5$points_in_vertex[3]
	m_kde_adult_5.40.5.n3.vec<-as.vector(unlist(m_kde_adult_5.40.5.n3))
m_kde_adult_5.40.5.n4<-m_kde_adult_5.40.5$points_in_vertex[4]
	m_kde_adult_5.40.5.n4.vec<-as.vector(unlist(m_kde_adult_5.40.5.n4)) 
m_kde_adult_5.40.5.n5<-m_kde_adult_5.40.5 $points_in_vertex[5]
	m_kde_adult_5.40.5.n5.vec<-as.vector(unlist(m_kde_adult_5.40.5.n5))

##map the ID’s of each Mapper vertex point to the actual Adult One Hot DF4 dataset
tda.m_kde_adult_5.40.5.n1.vec<-adult.one_hot_df4[m_kde_adult_5.40.5.n1.vec,]
tda.m_kde_adult_5.40.5.n2.vec<-adult.one_hot_df4[m_kde_adult_5.40.5.n2.vec,]
tda.m_kde_adult_5.40.5.n3.vec<-adult.one_hot_df4[m_kde_adult_5.40.5.n3.vec,]
tda.m_kde_adult_5.40.5.n4.vec<-adult.one_hot_df4[m_kde_adult_5.40.5.n4.vec,]
tda.m_kde_adult_5.40.5.n5.vec<-adult.one_hot_df4[m_kde_adult_5.40.5.n5.vec,]
```



```{r Partition_Adult_onehot_df4_dataset_into_training_(0,7)_and_test_(0.3)_sest_using_caret}

library(caret)

#Prepare Adult dataset for Mapper 1D algorithm
adult_df1<-adult[,15]
adult.one_hot_df1<-cbind(adult.one_hot_df,adult_df1)
adult.one_hot_df2<-adult.one_hot_df1[,c(1,11,28,64,65,66,109)]
adult.one_hot_df3<-adult.one_hot_df1[,c(1,11,28,62,63,64,65,66)]
adult.one_hot_df4<-adult.one_hot_df1[,-c(109,110)]

trainIndex <- createDataPartition(adult.one_hot_df4$adult_df1, p = .7, 
                                  list = FALSE, 
                                  times = 1)

head(trainIndex)

adult.one_hot_df4Train <- adult.one_hot_df4[ trainIndex,]
adult.one_hot_df4Test  <- adult.one_hot_df4[-trainIndex,]
```

```{r Prepare_Adult_onehot_df4_dataset_for_3_fold_CV}

#Train Control: k-Fold Cross-validation basis for all models 
fitControl <- trainControl(## 10-fold CV
                           method = "cv",
                           number = 3)

```

```{r Fit_the_non_TDA_Assisted_Algorithms_with_the_3-folds_for_cv:_extract_folds_for_TDA_fr}

#Non-TDA-Assited
rfGrid<-expand.grid(mtry = (1:20)*50)
#Random Forest 
adultRfFit <- train(as.factor(adult_df1) ~ ., data = adult.one_hot_df4Train, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'),				      
                 metric='Accuracy')

adultRfFit
adultRfFit$resample
ad_rf_fit_re<-adultRfFit$resample[1]


summary(adultRfFit)
vip(adultRfFit,25) + ggtitle("non-TDA-Assisted: RF")

# Predict outcome using model from training data based on testing data
predictions <- predict(adultRfFit, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
rf_cf<-confusionMatrix(data=predictions, as.factor(adult.one_hot_df4Test$adult_df1))
rf_cf
rf_cf$overall
rf_cf_ov_acc<-rf_cf$overall[1]
rf_cf$byClass
rf_cf_pre_rec_f1<-rf_cf$byClass[5:7]

##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node1

Adult_TDA_PC_5.40.5_n1_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n1.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'), 
                 metric='Accuracy')

Adult_TDA_PC_5.40.5_n1_RfFit0
Adult_TDA_PC_5.40.5_n1_RfFit0$resample
ad_tda_pc_5.40.5_n1_rf_fit0_re<-Adult_TDA_PC_5.40.5_n1_RfFit0$resample[1]


summary(Adult_TDA_PC_5.40.5_n1_RfFit0)

vip(Adult_TDA_PC_5.40.5_n1_RfFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n1_RfFit TDA-Assited RF")


# Predict outcome using Adult_TDA_PC_5.40.5_n1_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n1_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n1_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n1_rf_cf0
ad_tda_pc_5.40.5_n1_rf_cf0 
ad_tda_pc_5.40.5_n1_rf_cf0$overall
ad_tda_pc_5.40.5_n1_rf_cf0_ov_acc<-ad_tda_pc_5.40.5_n1_rf_cf0$overall[1]
ad_tda_pc_5.40.5_n1_rf_cf0$byClass
ad_tda_pc_5.40.5_n1_rf_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n1_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_rf_n1_3_fold<-(ad_rf_fit_re-ad_tda_pc_5.40.5_n1_rf_fit0_re)
diff_tda_pca_5.40.5_rf_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf_n1_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n1_3_fold_odds.left<-bst_tda_pca_5.40.5_rf.n1_3_fold$probLeft/bst_tda_pca_5.40.5_rf.n1_3_fold$probRight
bst_tda_pca_5.40.5_rf.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf_n1_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n1_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf_n1_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n1_3_fold

# Rope Plot
plot(rope(as.matrix(diff_tda_pca_5.40.5_rf_n1_3_fold),c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n1_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf_n1_3_fold))
#bf_tda_pca_5.40.5_rf.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_rf_n1_3_fold))


### Test set diff
diff_tda_pca_5.40.5_rf.n1_test<-(rf_cf_ov_acc-ad_tda_pc_5.40.5_n1_rf_cf0_ov_acc)
diff_tda_pca_5.40.5_rf.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n1_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf.n1_test),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n1_test_odds.left<-bst_tda_pca_5.40.5_rf.n1_test$probLeft/bst_tda_pca_5.40.5_rf.n1_test$probRight
bst_tda_pca_5.40.5_rf.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n1_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf.n1_test),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n1_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf.n1_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n1_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_rf.n1_test)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n1_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf.n1_test)) #bf_tda_pca_5.40.5_rf.n1_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_rf.n1_test))

##Node2

Adult_TDA_PC_5.40.5_n2_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'), 
                 metric='Accuracy')
				         
Adult_TDA_PC_5.40.5_n2_RfFit0
Adult_TDA_PC_5.40.5_n2_RfFit0$resample
ad_tda_pc_5.40.5_n2_rf_fit0_re<-Adult_TDA_PC_5.40.5_n2_RfFit0$resample[1]


summary(Adult_TDA_PC_5.40.5_n2_RfFit0)

vip(Adult_TDA_PC_5.40.5_n2_RfFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n2_RfFit TDA-Assited RF")


# Predict outcome using Adult_TDA_PC_5.40.5_n2_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n2_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n2_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n2_rf_cf0
ad_tda_pc_5.40.5_n2_rf_cf0 
ad_tda_pc_5.40.5_n2_rf_cf0$overall
ad_tda_pc_5.40.5_n2_rf_cf0_ov_acc<-ad_tda_pc_5.40.5_n2_rf_cf0$overall[1]
ad_tda_pc_5.40.5_n2_rf_cf0$byClass
ad_tda_pc_5.40.5_n2_rf_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n2_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_rf_n2_3_fold<-(ad_rf_fit_re-ad_tda_pc_5.40.5_n2_rf_fit0_re)
diff_tda_pca_5.40.5_rf_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf_n2_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n2_3_fold_odds.left<-bst_tda_pca_5.40.5_rf.n2_3_fold$probLeft/bst_tda_pca_5.40.5_rf.n2_3_fold$probRight
bst_tda_pca_5.40.5_rf.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf_n2_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n2_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf_n2_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n2_3_fold

# Rope Plot
plot(rope(as.matrix(diff_tda_pca_5.40.5_rf_n2_3_fold),c(-0.01,0.01)))


#BayesFactor
#bf_tda_pca_5.40.5_rf.n2_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf_n2_3_fold))
#bf_tda_pca_5.40.5_rf.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_rf_n2_3_fold))


### Test set diff
diff_tda_pca_5.40.5_rf.n2_test<-(rf_cf_ov_acc-ad_tda_pc_5.40.5_n2_rf_cf0_ov_acc)
diff_tda_pca_5.40.5_rf.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n2_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf.n2_test),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n2_test_odds.left<-bst_tda_pca_5.40.5_rf.n2_test$probLeft/bst_tda_pca_5.40.5_rf.n2_test$probRight
bst_tda_pca_5.40.5_rf.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n2_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf.n2_test),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n2_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf.n2_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n2_test

# Rope Plot
#plot(rope(as.matrix(diff_tda_pca_5.40.5_rf.n2_test),c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n2_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf.n2_test)) #bf_tda_pca_5.40.5_rf.n2_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_rf.n2_test))

##Node3

Adult_TDA_PC_5.40.5_n3_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n3.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'), 
                 metric='Accuracy')

Adult_TDA_PC_5.40.5_n3_RfFit0
Adult_TDA_PC_5.40.5_n3_RfFit0$resample
ad_tda_pc_5.40.5_n3_rf_fit0_re<-Adult_TDA_PC_5.40.5_n3_RfFit0$resample[1]


summary(Adult_TDA_PC_5.40.5_n3_RfFit0)

vip(Adult_TDA_PC_5.40.5_n3_RfFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n3_RfFit TDA-Assited RF")



# Predict outcome using Adult_TDA_PC_5.40.5_n3_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n3_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n3_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n3_rf_cf0
ad_tda_pc_5.40.5_n3_rf_cf0 
ad_tda_pc_5.40.5_n3_rf_cf0$overall
ad_tda_pc_5.40.5_n3_rf_cf0_ov_acc<-ad_tda_pc_5.40.5_n3_rf_cf0$overall[1]
ad_tda_pc_5.40.5_n3_rf_cf0$byClass
ad_tda_pc_5.40.5_n3_rf_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n3_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_rf_n3_3_fold<-(ad_rf_fit_re-ad_tda_pc_5.40.5_n3_rf_fit0_re)
diff_tda_pca_5.40.5_rf_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf_n3_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n3_3_fold_odds.left<-bst_tda_pca_5.40.5_rf.n3_3_fold$probLeft/bst_tda_pca_5.40.5_rf.n3_3_fold$probRight
bst_tda_pca_5.40.5_rf.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf_n3_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n3_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf_n3_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n2_3_fold

# Rope Plot
plot(rope(as.matrix(diff_tda_pca_5.40.5_rf_n3_3_fold),c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n3_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf_n3_3_fold))
#bf_tda_pca_5.40.5_rf.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_rf_n3_3_fold))

### Test set diff
diff_tda_pca_5.40.5_rf.n3_test<-(rf_cf_ov_acc-ad_tda_pc_5.40.5_n3_rf_cf0_ov_acc)
diff_tda_pca_5.40.5_rf.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n3_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf.n3_test),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n3_test_odds.left<-bst_tda_pca_5.40.5_rf.n3_test$probLeft/bst_tda_pca_5.40.5_rf.n3_test$probRight
bst_tda_pca_5.40.5_rf.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n3_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf.n3_test),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n3_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf.n3_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n3_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_rf.n3_test))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n3_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf.n3_test)) #bf_tda_pca_5.40.5_rf.n3_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_rf.n2_test)

##Node4

Adult_TDA_PC_5.40.5_n4_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n4.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'), 
                 metric='Accuracy')

Adult_TDA_PC_5.40.5_n4_RfFit0
Adult_TDA_PC_5.40.5_n4_RfFit0$resample
ad_tda_pc_5.40.5_n4_rf_fit0_re<-Adult_TDA_PC_5.40.5_n4_RfFit0$resample[1]


summary(Adult_TDA_PC_5.40.5_n4_RfFit0)

vip(Adult_TDA_PC_5.40.5_n4_RfFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n4_RfFit TDA-Assited RF")



# Predict outcome using Adult_TDA_PC_5.40.5_n4_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n4_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n4_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n4_rf_cf0
ad_tda_pc_5.40.5_n4_rf_cf0 
ad_tda_pc_5.40.5_n4_rf_cf0$overall
ad_tda_pc_5.40.5_n4_rf_cf0_ov_acc<-ad_tda_pc_5.40.5_n4_rf_cf0$overall[1]
ad_tda_pc_5.40.5_n4_rf_cf0$byClass
ad_tda_pc_5.40.5_n4_rf_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n4_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_rf_n4_3_fold<-(ad_rf_fit_re-ad_tda_pc_5.40.5_n4_rf_fit0_re)
diff_tda_pca_5.40.5_rf_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf_n4_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n4_3_fold_odds.left<-bst_tda_pca_5.40.5_rf.n4_3_fold$probLeft/bst_tda_pca_5.40.5_rf.n4_3_fold$probRight
bst_tda_pca_5.40.5_rf.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf_n4_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n4_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf_n4_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n4_3_fold

# Rope Plot
plot(rope(as.matrix(diff_tda_pca_5.40.5_rf_n4_3_fold),c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n4_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf_n4_3_fold))
#bf_tda_pca_5.40.5_rf.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_rf_n4_3_fold))

### Test set diff
diff_tda_pca_5.40.5_rf.n4_test<-(rf_cf_ov_acc-ad_tda_pc_5.40.5_n4_rf_cf0_ov_acc)
diff_tda_pca_5.40.5_rf.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n4_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf.n4_test),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n4_test_odds.left<-bst_tda_pca_5.40.5_rf.n4_test$probLeft/bst_tda_pca_5.40.5_rf.n4_test$probRight
bst_tda_pca_5.40.5_rf.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n4_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf.n4_test),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n4_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf.n4_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n4_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_rf.n4_test))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n4_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf.n4_test)) #bf_tda_pca_5.40.5_rf.n4_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_rf.n4_test))

##Node5

Adult_TDA_PC_5.40.5_n5_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n5.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'), 
                 metric='Accuracy')

Adult_TDA_PC_5.40.5_n5_RfFit0
Adult_TDA_PC_5.40.5_n5_RfFit0$resample
ad_tda_pc_5.40.5_n5_rf_fit0_re<-Adult_TDA_PC_5.40.5_n5_RfFit0$resample[1]


summary(Adult_TDA_PC_5.40.5_n5_RfFit0)

vip(Adult_TDA_PC_5.40.5_n5_RfFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n5_RfFit TDA-Assited RF")



# Predict outcome using Adult_TDA_PC_5.40.5_n5_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n5_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n5_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n5_rf_cf0
ad_tda_pc_5.40.5_n5_rf_cf0 
ad_tda_pc_5.40.5_n5_rf_cf0$overall
ad_tda_pc_5.40.5_n5_rf_cf0_ov_acc<-ad_tda_pc_5.40.5_n5_rf_cf0$overall[1]
ad_tda_pc_5.40.5_n5_rf_cf0$byClass
ad_tda_pc_5.40.5_n5_rf_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n5_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_rf_n5_3_fold<-(ad_rf_fit_re-ad_tda_pc_5.40.5_n5_rf_fit0_re)
diff_tda_pca_5.40.5_rf_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf_n5_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n5_3_fold_odds.left<-bst_tda_pca_5.40.5_rf.n5_3_fold$probLeft/bst_tda_pca_5.40.5_rf.n5_3_fold$probRight
bst_tda_pca_5.40.5_rf.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf_n5_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n5_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf_n5_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n5_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_rf_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n5_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf_n5_3_fold))
#bf_tda_pca_5.40.5_rf.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_rf_n5_3_fold))

### Test set diff
diff_tda_pca_5.40.5_rf.n5_test<-(rf_cf_ov_acc-ad_tda_pc_5.40.5_n5_rf_cf0_ov_acc)
diff_tda_pca_5.40.5_rf.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_rf.n5_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_rf.n5_test),-0.01,0.01)
bst_tda_pca_5.40.5_rf.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_rf.n5_test_odds.left<-bst_tda_pca_5.40.5_rf.n5_test$probLeft/bst_tda_pca_5.40.5_rf.n5_test$probRight
bst_tda_pca_5.40.5_rf.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_rf.n5_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_rf.n5_test),-0.01,0.01)
bsr_tda_pca_5.40.5_rf.n5_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_rf.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_rf.n5_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_rf.n5_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_rf.n5_test))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n5_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_rf.n5_test)) #bf_tda_pca_5.40.5_rf.n5_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_rf.n5_test))

##With TDA KDE filter 5 intervals, 50% overlap, 5 bins 
##Node1

Adult_TDA_KDE_5.40.5_n1_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n1.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'), 
                 metric='Accuracy')

Adult_TDA_KDE_5.40.5_n1_RfFit0
Adult_TDA_KDE_5.40.5_n1_RfFit0$resample
ad_tda_kde_5.40.5_n1_rf_fit0_re<-Adult_TDA_KDE_5.40.5_n1_RfFit0$resample[1]


summary(Adult_TDA_KDE_5.40.5_n1_RfFit0)

vip(Adult_TDA_KDE_5.40.5_n1_RfFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n1_RfFit TDA-Assited RF")



# Predict outcome using Adult_TDA_KDE_5.40.5_n1_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n1_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n1_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n1_rf_cf0
ad_tda_kde_5.40.5_n1_rf_cf0 
ad_tda_kde_5.40.5_n1_rf_cf0$overall
ad_tda_kde_5.40.5_n1_rf_cf0_ov_acc<-ad_tda_kde_5.40.5_n1_rf_cf0$overall[1]
ad_tda_kde_5.40.5_n1_rf_cf0$byClass
ad_tda_kde_5.40.5_n1_rf_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n1_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_rf_n1_3_fold<-(ad_rf_fit_re-ad_tda_kde_5.40.5_n1_rf_fit0_re)
diff_tda_kde_5.40.5_rf_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf_n1_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n1_3_fold_odds.left<-bst_tda_kde_5.40.5_rf.n1_3_fold$probLeft/bst_tda_kde_5.40.5_rf.n1_3_fold$probRight
bst_tda_kde_5.40.5_rf.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf_n1_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n1_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf_n1_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n1_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_rf_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n1_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf_n1_3_fold))
#bf_tda_kde_5.40.5_rf.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_rf_n1_3_fold))


### Test set diff
diff_tda_kde_5.40.5_rf.n1_test<-(rf_cf_ov_acc-ad_tda_kde_5.40.5_n1_rf_cf0_ov_acc)
diff_tda_kde_5.40.5_rf.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n1_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf.n1_test),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n1_test_odds.left<-bst_tda_kde_5.40.5_rf.n1_test$probLeft/bst_tda_kde_5.40.5_rf.n1_test$probRight
bst_tda_kde_5.40.5_rf.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n1_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf.n1_test),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n1_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf.n1_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n1_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_rf.n1_test))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n1_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf.n1_test)) #bf_tda_kde_5.40.5_rf.n1_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_rf.n1_test))

##Node2

Adult_TDA_KDE_5.40.5_n2_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n2.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'),				      
                 metric='Accuracy')

Adult_TDA_KDE_5.40.5_n2_RfFit0
Adult_TDA_KDE_5.40.5_n2_RfFit0$resample
ad_tda_KDE_5.40.5_n2_rf_fit0_re<-Adult_TDA_KDE_5.40.5_n2_RfFit0$resample[1]


summary(Adult_TDA_KDE_5.40.5_n2_RfFit0)

vip(Adult_TDA_KDE_5.40.5_n2_RfFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n2_RfFit TDA-Assited RF")


# Predict outcome using Adult_TDA_KDE_5.40.5_n2_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n2_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n2_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n2_rf_cf0
ad_tda_kde_5.40.5_n2_rf_cf0 
ad_tda_kde_5.40.5_n2_rf_cf0$overall
ad_tda_kde_5.40.5_n2_rf_cf0_ov_acc<-ad_tda_kde_5.40.5_n2_rf_cf0$overall[1]
ad_tda_kde_5.40.5_n2_rf_cf0$byClass
ad_tda_kde_5.40.5_n2_rf_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n2_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_rf_n2_3_fold<-(ad_rf_fit_re-ad_tda_KDE_5.40.5_n2_rf_fit0_re)
diff_tda_kde_5.40.5_rf_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf_n2_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n2_3_fold_odds.left<-bst_tda_kde_5.40.5_rf.n2_3_fold$probLeft/bst_tda_kde_5.40.5_rf.n2_3_fold$probRight
bst_tda_kde_5.40.5_rf.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf_n2_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n2_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf_n2_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n2_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_rf_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n2_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf_n2_3_fold))
#bf_tda_kde_5.40.5_rf.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_rf_n2_3_fold))


### Test set diff
diff_tda_kde_5.40.5_rf.n2_test<-(rf_cf_ov_acc-ad_tda_kde_5.40.5_n2_rf_cf0_ov_acc)
diff_tda_kde_5.40.5_rf.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n2_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf.n2_test),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n2_test_odds.left<-bst_tda_kde_5.40.5_rf.n2_test$probLeft/bst_tda_kde_5.40.5_rf.n2_test$probRight
bst_tda_kde_5.40.5_rf.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n2_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf.n2_test),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n2_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf.n2_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n2_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_rf.n2_test))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n2_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf.n2_test)) #bf_tda_kde_5.40.5_rf.n2_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_rf.n2_test))

##Node3

Adult_TDA_KDE_5.40.5_n3_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n3.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'),				      
                 metric='Accuracy')

Adult_TDA_KDE_5.40.5_n3_RfFit0
Adult_TDA_KDE_5.40.5_n3_RfFit0$resample
ad_tda_kde_5.40.5_n3_rf_fit0_re<-Adult_TDA_KDE_5.40.5_n3_RfFit0$resample[1]


summary(Adult_TDA_KDE_5.40.5_n3_RfFit0)

vip(Adult_TDA_KDE_5.40.5_n3_RfFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n3_RfFit TDA-Assited RF")


# Predict outcome using Adult_TDA_KDE_5.40.5_n3_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n3_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n3_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n3_rf_cf0
ad_tda_kde_5.40.5_n3_rf_cf0 
ad_tda_kde_5.40.5_n3_rf_cf0$overall
ad_tda_kde_5.40.5_n3_rf_cf0_ov_acc<-ad_tda_kde_5.40.5_n3_rf_cf0$overall[1]
ad_tda_kde_5.40.5_n3_rf_cf0$byClass
ad_tda_kde_5.40.5_n3_rf_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n3_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_rf_n3_3_fold<-(ad_rf_fit_re-ad_tda_kde_5.40.5_n3_rf_fit0_re)
diff_tda_kde_5.40.5_rf_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf_n3_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n3_3_fold_odds.left<-bst_tda_kde_5.40.5_rf.n3_3_fold$probLeft/bst_tda_kde_5.40.5_rf.n3_3_fold$probRight
bst_tda_kde_5.40.5_rf.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf_n3_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n3_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf_n3_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n3_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_rf_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n3_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf_n3_3_fold))
#bf_tda_kde_5.40.5_rf.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_rf_n3_3_fold))


### Test set diff
diff_tda_kde_5.40.5_rf.n3_test<-(rf_cf_ov_acc-ad_tda_kde_5.40.5_n3_rf_cf0_ov_acc)
diff_tda_kde_5.40.5_rf.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n3_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf.n3_test),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n3_test_odds.left<-bst_tda_kde_5.40.5_rf.n3_test$probLeft/bst_tda_kde_5.40.5_rf.n3_test$probRight
bst_tda_kde_5.40.5_rf.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n3_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf.n3_test),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n3_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf.n3_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n3_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_rf.n3_test))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n3_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf.n3_test)) #bf_tda_kde_5.40.5_rf.n3_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_rf.n3_test))

##Node4

Adult_TDA_KDE_5.40.5_n4_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n4.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'),				      
                 metric='Accuracy')

Adult_TDA_KDE_5.40.5_n4_RfFit0
Adult_TDA_KDE_5.40.5_n4_RfFit0$resample
ad_tda_kde_5.40.5_n4_rf_fit0_re<-Adult_TDA_KDE_5.40.5_n4_RfFit0$resample[1]


summary(Adult_TDA_KDE_5.40.5_n4_RfFit0)

vip(Adult_TDA_KDE_5.40.5_n4_RfFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n4_RfFit TDA-Assited RF")


# Predict outcome using Adult_TDA_KDE_5.40.5_n4_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n4_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n4_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n4_rf_cf0
ad_tda_kde_5.40.5_n4_rf_cf0 
ad_tda_kde_5.40.5_n4_rf_cf0$overall
ad_tda_kde_5.40.5_n4_rf_cf0_ov_acc<-ad_tda_kde_5.40.5_n4_rf_cf0$overall[1]
ad_tda_kde_5.40.5_n4_rf_cf0$byClass
ad_tda_kde_5.40.5_n4_rf_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n4_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_rf_n4_3_fold<-(ad_rf_fit_re-ad_tda_kde_5.40.5_n4_rf_fit0_re)
diff_tda_kde_5.40.5_rf_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf_n4_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n4_3_fold_odds.left<-bst_tda_kde_5.40.5_rf.n4_3_fold$probLeft/bst_tda_kde_5.40.5_rf.n4_3_fold$probRight
bst_tda_kde_5.40.5_rf.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf_n4_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n4_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf_n4_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n4_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_rf_n4_3_fold,c(-0.01,0.01)))


### Test set diff
diff_tda_kde_5.40.5_rf.n4_test<-(rf_cf_ov_acc-ad_tda_kde_5.40.5_n4_rf_cf0_ov_acc)
diff_tda_kde_5.40.5_rf.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n4_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf.n4_test),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n4_test

# Odds Left Bayesian Sign Test 
#BayesFactor
#bf_tda_kde_5.40.5_rf.n4_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf_n4_3_fold))
#bf_tda_kde_5.40.5_rf.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_rf_n4_3_fold))


bst_tda_kde_5.40.5_rf.n4_test_odds.left<-bst_tda_kde_5.40.5_rf.n4_test$probLeft/bst_tda_kde_5.40.5_rf.n4_test$probRight
bst_tda_kde_5.40.5_rf.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n4_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf.n4_test),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n4_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf.n4_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n4_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_rf.n4_test))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n4_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf.n4_test)) #bf_tda_kde_5.40.5_rf.n4_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_rf.n4_test))

##Node5

Adult_TDA_KDE_5.40.5_n5_RfFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n5.vec, 
                 Importance = T,
                 method = 'rf', 
                 trControl = fitControl,
                 tuneGrid = rfGrid, preProc = c('center','scale'),				      
                 metric='Accuracy')

Adult_TDA_KDE_5.40.5_n5_RfFit0
Adult_TDA_KDE_5.40.5_n5_RfFit0$resample
ad_tda_kde_5.40.5_n5_rf_fit0_re<-Adult_TDA_KDE_5.40.5_n5_RfFit0$resample[1]


summary(Adult_TDA_KDE_5.40.5_n5_RfFit0)

vip(Adult_TDA_KDE_5.40.5_n5_RfFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n5_RfFit TDA-Assited RF")


# Predict outcome using Adult_TDA_KDE_5.40.5_n5_RfFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n5_RfFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n5_rf_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n5_rf_cf0
ad_tda_kde_5.40.5_n5_rf_cf0 
ad_tda_kde_5.40.5_n5_rf_cf0$overall
ad_tda_kde_5.40.5_n5_rf_cf0_ov_acc<-ad_tda_kde_5.40.5_n5_rf_cf0$overall[1]
ad_tda_kde_5.40.5_n5_rf_cf0$byClass
ad_tda_kde_5.40.5_n5_rf_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n5_rf_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_rf_n5_3_fold<-(ad_rf_fit_re-ad_tda_kde_5.40.5_n5_rf_fit0_re)
diff_tda_kde_5.40.5_rf_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf_n5_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n5_3_fold_odds.left<-bst_tda_kde_5.40.5_rf.n5_3_fold$probLeft/bst_tda_kde_5.40.5_rf.n5_3_fold$probRight
bst_tda_kde_5.40.5_rf.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf_n5_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n5_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf_n5_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n5_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_rf_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n5_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf_n5_3_fold))
#bf_tda_kde_5.40.5_rf.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_rf_n5_3_fold))


### Test set diff
diff_tda_kde_5.40.5_rf.n5_test<-(rf_cf_ov_acc-ad_tda_kde_5.40.5_n5_rf_cf0_ov_acc)
diff_tda_kde_5.40.5_rf.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_rf.n5_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_rf.n5_test),-0.01,0.01)
bst_tda_kde_5.40.5_rf.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_rf.n5_test_odds.left<-bst_tda_kde_5.40.5_rf.n5_test$probLeft/bst_tda_kde_5.40.5_rf.n5_test$probRight
bst_tda_kde_5.40.5_rf.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_rf.n5_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_rf.n5_test),-0.01,0.01)
bsr_tda_kde_5.40.5_rf.n5_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_rf.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_rf.n5_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_rf.n5_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_rf.n5_test))

#BayesFactor
#bf_tda_kde_5.40.5_rf.n5_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_rf.n5_test)) #bf_tda_kde_5.40.5_rf.n5_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_rf.n5_test))

##Non-TDA-Assisted

svmGrid<-expand.grid(sigma = c(0.1, 1, 10), C = (1:5*0.25))

#Support Vector Machine-Radial Basis 
adultSvmFit <- train(as.factor(adult_df1) ~ ., data = adult.one_hot_df4Train, 
            	   Importance = T,
            	   method = 'svmRadial', 
                 trControl = fitControl,
				         tuneGrid = svmGrid, preProc = c('center','scale'),
				         metric='Accuracy')

adultSvmFit
adultSvmFit$resample
ad_svm_fit_re<-adultSvmFit$resample[1]

summary(adultSvmFit)

#vip(adultSvmFit, 25) + ggtitle("non-TDA-Assited Svm")

# Predict outcome using model from training data based on testing data
predictions <- predict(adultSvmFit, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
svm_cf<-confusionMatrix(data=predictions, as.factor(adult.one_hot_df4Test$adult_df1))
svm_cf
svm_cf$overall
svm_cf_ov_acc<-svm_cf$overall[1]
svm_cf$byClass
svm_cf_pr_rec_f1<-svm_cf$byClass[5:7]

##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node1

Adult_TDA_PC_5.40.5_n1_SvmFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_PC_5.40.5_n1_SvmFit0
Adult_TDA_PC_5.40.5_n1_SvmFit0$resample
ad_tda_pc_5.40.5_n1_svm_fit_re<-Adult_TDA_PC_5.40.5_n1_SvmFit0 $resample[1]

summary(Adult_TDA_PC_5.40.5_n1_SvmFit0)

#vip(Adult_TDA_PC_5.40.5_n1_SvmFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n1_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_PC_5.40.5_n1_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n1_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n1_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n1_svm_cf0
ad_tda_pc_5.40.5_n1_svm_cf0 
ad_tda_pc_5.40.5_n1_svm_cf0$overall
ad_tda_pc_5.40.5_n1_svm_cf0_ov_acc<-ad_tda_pc_5.40.5_n1_svm_cf0$overall[1]
ad_tda_pc_5.40.5_n1_svm_cf0$byClass
ad_tda_pc_5.40.5_n1_svm_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n1_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_svm_n1_3_fold<-(ad_svm_fit_re - ad_tda_pc_5.40.5_n1_svm_fit_re)
diff_tda_pca_5.40.5_svm_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm_n1_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n1_3_fold_odds.left<-bst_tda_pca_5.40.5_svm.n1_3_fold$probLeft/bst_tda_pca_5.40.5_svm.n1_3_fold$probRight
bst_tda_pca_5.40.5_svm.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm_n1_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n1_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm_n1_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n1_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_svm_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n1_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm_n1_3_fold))
#bf_tda_pca_5.40.5_rf.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_svm_n1_3_fold))


### Test set diff
diff_tda_pca_5.40.5_svm.n1_test<-(svm_cf_ov_acc - ad_tda_pc_5.40.5_n1_svm_cf0_ov_acc)
diff_tda_pca_5.40.5_svm.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n1_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm.n1_test),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n1_test_odds.left<-bst_tda_pca_5.40.5_svm.n1_test$probLeft/bst_tda_pca_5.40.5_svm.n1_test$probRight
bst_tda_pca_5.40.5_svm.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n1_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm.n1_test),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n1_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm.n1_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n1_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_svm.n1_test)))

#BayesFactor
#bf_tda_pca_5.40.5_svm.n1_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm.n1_test)) #bf_tda_pca_5.40.5_svm.n1_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_svm.n1_test))

##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node2

Adult_TDA_PC_5.40.5_n2_SvmFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_PC_5.40.5_n2_SvmFit0
Adult_TDA_PC_5.40.5_n2_SvmFit0$resample
ad_tda_pc_5.40.5_n2_svm_fit_re<-Adult_TDA_PC_5.40.5_n2_SvmFit0 $resample[1]

summary(Adult_TDA_PC_5.40.5_n2_SvmFit0)

#vip(Adult_TDA_PC_5.40.5_n2_SvmFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n2_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_PC_5.40.5_n2_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n2_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n2_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n2_svm_cf0
ad_tda_pc_5.40.5_n2_svm_cf0 
ad_tda_pc_5.40.5_n2_svm_cf0$overall
ad_tda_pc_5.40.5_n2_svm_cf0_ov_acc<-ad_tda_pc_5.40.5_n2_svm_cf0$overall[1]
ad_tda_pc_5.40.5_n2_svm_cf0$byClass
ad_tda_pc_5.40.5_n2_svm_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n2_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_svm_n2_3_fold<-(ad_svm_fit_re - ad_tda_pc_5.40.5_n2_svm_fit_re)
diff_tda_pca_5.40.5_svm_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm_n2_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n2_3_fold_odds.left<-bst_tda_pca_5.40.5_svm.n2_3_fold$probLeft/bst_tda_pca_5.40.5_svm.n2_3_fold$probRight
bst_tda_pca_5.40.5_svm.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm_n2_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n2_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm_n2_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n2_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_svm_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n2_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm_n2_3_fold))
#bf_tda_pca_5.40.5_rf.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_svm_n2_3_fold))


### Test set diff
diff_tda_pca_5.40.5_svm.n2_test<-(svm_cf_ov_acc - ad_tda_pc_5.40.5_n2_svm_cf0_ov_acc)
diff_tda_pca_5.40.5_svm.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n2_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm.n2_test),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n2_test_odds.left<-bst_tda_pca_5.40.5_svm.n2_test$probLeft/bst_tda_pca_5.40.5_svm.n2_test$probRight
bst_tda_pca_5.40.5_svm.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n2_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm.n2_test),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n2_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm.n2_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n2_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_svm.n2_test)))

#BayesFactor
#bf_tda_pca_5.40.5_svm.n2_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm.n2_test)) #bf_tda_pca_5.40.5_svm.n2_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_svm.n2_test))

##Node3

Adult_TDA_PC_5.40.5_n3_SvmFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n3.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_PC_5.40.5_n3_SvmFit0
Adult_TDA_PC_5.40.5_n3_SvmFit0$resample
ad_tda_pc_5.40.5_n3_svm_fit_re<-Adult_TDA_PC_5.40.5_n3_SvmFit0 $resample[1]

summary(Adult_TDA_PC_5.40.5_n3_SvmFit0)

#vip(Adult_TDA_PC_5.40.5_n3_SvmFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n3_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_PC_5.40.5_n3_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n3_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n3_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n3_svm_cf0
ad_tda_pc_5.40.5_n3_svm_cf0 
ad_tda_pc_5.40.5_n3_svm_cf0$overall
ad_tda_pc_5.40.5_n3_svm_cf0_ov_acc<-ad_tda_pc_5.40.5_n3_svm_cf0$overall[1]
ad_tda_pc_5.40.5_n3_svm_cf0$byClass
ad_tda_pc_5.40.5_n3_svm_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n3_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_svm_n3_3_fold<-(ad_svm_fit_re - ad_tda_pc_5.40.5_n3_svm_fit_re)
diff_tda_pca_5.40.5_svm_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm_n3_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n3_3_fold_odds.left<-bst_tda_pca_5.40.5_svm.n3_3_fold$probLeft/bst_tda_pca_5.40.5_svm.n3_3_fold$probRight
bst_tda_pca_5.40.5_svm.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm_n3_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n3_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm_n3_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n3_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_svm_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n3_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm_n3_3_fold))
#bf_tda_pca_5.40.5_rf.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_svm_n3_3_fold))


### Test set diff
diff_tda_pca_5.40.5_svm.n3_test<-(svm_cf_ov_acc - ad_tda_pc_5.40.5_n3_svm_cf0_ov_acc)
diff_tda_pca_5.40.5_svm.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n3_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm.n3_test),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n3_test_odds.left<-bst_tda_pca_5.40.5_svm.n3_test$probLeft/bst_tda_pca_5.40.5_svm.n3_test$probRight
bst_tda_pca_5.40.5_svm.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n3_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm.n3_test),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n3_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm.n3_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n3_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_svm.n3_test)))

#BayesFactor
#bf_tda_pca_5.40.5_svm.n3_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm.n3_test)) #bf_tda_pca_5.40.5_svm.n3_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_svm.n3_test))


##Node4

Adult_TDA_PC_5.40.5_n4_SvmFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n4.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_PC_5.40.5_n4_SvmFit0
Adult_TDA_PC_5.40.5_n4_SvmFit0$resample
ad_tda_pc_5.40.5_n4_svm_fit_re<-Adult_TDA_PC_5.40.5_n4_SvmFit0 $resample[1]

summary(Adult_TDA_PC_5.40.5_n4_SvmFit0)
#vip(Adult_TDA_PC_5.40.5_n4_SvmFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n4_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_PC_5.40.5_n4_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n4_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n4_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n4_svm_cf0
ad_tda_pc_5.40.5_n4_svm_cf0 
ad_tda_pc_5.40.5_n4_svm_cf0$overall
ad_tda_pc_5.40.5_n4_svm_cf0_ov_acc<-ad_tda_pc_5.40.5_n4_svm_cf0$overall[1]
ad_tda_pc_5.40.5_n4_svm_cf0$byClass
ad_tda_pc_5.40.5_n4_svm_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n4_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_svm_n4_3_fold<-(ad_svm_fit_re - ad_tda_pc_5.40.5_n4_svm_fit_re)
diff_tda_pca_5.40.5_svm_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm_n4_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n4_3_fold_odds.left<-bst_tda_pca_5.40.5_svm.n4_3_fold$probLeft/bst_tda_pca_5.40.5_svm.n4_3_fold$probRight
bst_tda_pca_5.40.5_svm.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm_n4_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n4_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm_n4_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n4_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_svm_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n4_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm_n4_3_fold))
#bf_tda_pca_5.40.5_rf.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_svm_n4_3_fold))


### Test set diff
diff_tda_pca_5.40.5_svm.n4_test<-(svm_cf_ov_acc - ad_tda_pc_5.40.5_n4_svm_cf0_ov_acc)
diff_tda_pca_5.40.5_svm.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n4_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm.n4_test),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n4_test_odds.left<-bst_tda_pca_5.40.5_svm.n4_test$probLeft/bst_tda_pca_5.40.5_svm.n4_test$probRight
bst_tda_pca_5.40.5_svm.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n4_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm.n4_test),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n4_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm.n4_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n4_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_svm.n4_test)))

#BayesFactor
#bf_tda_pca_5.40.5_svm.n4_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm.n4_test)) #bf_tda_pca_5.40.5_svm.n4_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_svm.n4_test))

##Node5

Adult_TDA_PC_5.40.5_n5_SvmFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n5.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_PC_5.40.5_n5_SvmFit0
Adult_TDA_PC_5.40.5_n5_SvmFit0$resample
ad_tda_pc_5.40.5_n5_svm_fit_re<-Adult_TDA_PC_5.40.5_n5_SvmFit0 $resample[1]

summary(Adult_TDA_PC_5.40.5_n5_SvmFit0)
#vip(Adult_TDA_PC_5.40.5_n5_SvmFit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n5_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_PC_5.40.5_n5_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n5_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n5_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n5_svm_cf0
ad_tda_pc_5.40.5_n5_svm_cf0 
ad_tda_pc_5.40.5_n5_svm_cf0$overall
ad_tda_pc_5.40.5_n5_svm_cf0_ov_acc<-ad_tda_pc_5.40.5_n5_svm_cf0$overall[1]
ad_tda_pc_5.40.5_n5_svm_cf0$byClass
ad_tda_pc_5.40.5_n5_svm_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n5_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_svm_n5_3_fold<-(ad_svm_fit_re - ad_tda_pc_5.40.5_n5_svm_fit_re)
diff_tda_pca_5.40.5_svm_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm_n5_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n5_3_fold_odds.left<-bst_tda_pca_5.40.5_svm.n5_3_fold$probLeft/bst_tda_pca_5.40.5_svm.n5_3_fold$probRight
bst_tda_pca_5.40.5_svm.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm_n5_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n5_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm_n5_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n5_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_svm_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_rf.n5_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm_n5_3_fold))
#bf_tda_pca_5.40.5_rf.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_svm_n5_3_fold))


### Test set diff
diff_tda_pca_5.40.5_svm.n5_test<-(svm_cf_ov_acc - ad_tda_pc_5.40.5_n5_svm_cf0_ov_acc)
diff_tda_pca_5.40.5_svm.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_svm.n5_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_svm.n5_test),-0.01,0.01)
bst_tda_pca_5.40.5_svm.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_svm.n5_test_odds.left<-bst_tda_pca_5.40.5_svm.n5_test$probLeft/bst_tda_pca_5.40.5_svm.n5_test$probRight
bst_tda_pca_5.40.5_svm.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_svm.n5_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_svm.n5_test),-0.01,0.01)
bsr_tda_pca_5.40.5_svm.n5_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_svm.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_svm.n5_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_svm.n5_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_svm.n5_test)))

#BayesFactor
#bf_tda_pca_5.40.5_svm.n5_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_svm.n5_test)) #bf_tda_pca_5.40.5_svm.n5_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_svm.n5_test))


##With TDA KDE filter 5 intervals, 50% overlap, 5 bins 
##Node1


Adult_TDA_KDE_5.40.5_n1_SvmFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n1.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_KDE_5.40.5_n1_SvmFit0
Adult_TDA_KDE_5.40.5_n1_SvmFit0$resample
ad_tda_kde_5.40.5_n1_svm_fit_re<-Adult_TDA_KDE_5.40.5_n1_SvmFit0 $resample[1]

summary(Adult_TDA_PC_5.40.5_n1_SvmFit0)

#vip(Adult_TDA_KDE_5.40.5_n1_SvmFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n1_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_KDE_5.40.5_n1_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n1_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n1_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n1_svm_cf0
ad_tda_kde_5.40.5_n1_svm_cf0 
ad_tda_kde_5.40.5_n1_svm_cf0$overall
ad_tda_kde_5.40.5_n1_svm_cf0_ov_acc<-ad_tda_kde_5.40.5_n1_svm_cf0$overall[1]
ad_tda_kde_5.40.5_n1_svm_cf0$byClass
ad_tda_kde_5.40.5_n1_svm_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n1_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_svm_n1_3_fold<-(ad_svm_fit_re - ad_tda_kde_5.40.5_n1_svm_fit_re)
diff_tda_kde_5.40.5_svm_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm_n1_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n1_3_fold_odds.left<-bst_tda_kde_5.40.5_svm.n1_3_fold$probLeft/bst_tda_kde_5.40.5_svm.n1_3_fold$probRight
bst_tda_kde_5.40.5_svm.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm_n1_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n1_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm_n1_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n1_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_svm_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n1_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm_n1_3_fold))
#bf_tda_kde_5.40.5_svm.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_svm_n1_3_fold))


### Test set diff
diff_tda_kde_5.40.5_svm.n1_test<-(svm_cf_ov_acc-ad_tda_kde_5.40.5_n1_svm_cf0_ov_acc)
diff_tda_kde_5.40.5_svm.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n1_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm.n1_test),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n1_test_odds.left<-bst_tda_kde_5.40.5_svm.n1_test$probLeft/bst_tda_kde_5.40.5_svm.n1_test$probRight
bst_tda_kde_5.40.5_svm.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n1_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm.n1_test),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n1_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm.n1_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n1_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_svm.n1_test))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n1_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm.n1_test)) #bf_tda_kde_5.40.5_svm.n1_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_svm.n1_test))


##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node2

Adult_TDA_KDE_5.40.5_n2_SvmFit0 <- train(as.factor(adult_df1) ~ ., data =  tda.m_kde_adult_5.40.5.n2.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_KDE_5.40.5_n2_SvmFit0
Adult_TDA_KDE_5.40.5_n2_SvmFit0$resample
ad_tda_kde_5.40.5_n2_svm_fit_re<-Adult_TDA_KDE_5.40.5_n2_SvmFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n2_SvmFit0)

#vip(Adult_TDA_KDE_5.40.5_n2_SvmFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n2_SvmFit TDA-Assited Svm")
# Predict outcome using Adult_TDA_KDE_5.40.5_n2_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n2_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n2_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n2_svm_cf0
ad_tda_kde_5.40.5_n2_svm_cf0 
ad_tda_kde_5.40.5_n2_svm_cf0$overall
ad_tda_kde_5.40.5_n2_svm_cf0_ov_acc<-ad_tda_kde_5.40.5_n2_svm_cf0$overall[1]
ad_tda_kde_5.40.5_n2_svm_cf0$byClass
ad_tda_kde_5.40.5_n2_svm_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n2_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_svm_n2_3_fold<-(ad_svm_fit_re - ad_tda_kde_5.40.5_n2_svm_fit_re)
diff_tda_kde_5.40.5_svm_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm_n2_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n2_3_fold_odds.left<-bst_tda_kde_5.40.5_svm.n2_3_fold$probLeft/bst_tda_kde_5.40.5_svm.n2_3_fold$probRight
bst_tda_kde_5.40.5_svm.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm_n2_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n2_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm_n2_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n2_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_svm_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n2_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm_n2_3_fold))
#bf_tda_kde_5.40.5_svm.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_svm_n2_3_fold))


### Test set diff
diff_tda_kde_5.40.5_svm.n2_test<-(svm_cf_ov_acc-ad_tda_kde_5.40.5_n2_svm_cf0_ov_acc)
diff_tda_kde_5.40.5_svm.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n2_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm.n2_test),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n2_test_odds.left<-bst_tda_kde_5.40.5_svm.n2_test$probLeft/bst_tda_kde_5.40.5_svm.n2_test$probRight
bst_tda_kde_5.40.5_svm.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n2_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm.n2_test),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n2_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm.n2_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n2_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_svm.n2_test))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n2_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm.n2_test)) #bf_tda_kde_5.40.5_svm.n2_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_svm.n2_test))

##Node3

Adult_TDA_KDE_5.40.5_n3_SvmFit0 <- train(as.factor(adult_df1) ~ ., data =  tda.m_kde_adult_5.40.5.n3.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_KDE_5.40.5_n3_SvmFit0
Adult_TDA_KDE_5.40.5_n3_SvmFit0$resample
ad_tda_kde_5.40.5_n3_svm_fit_re<-Adult_TDA_KDE_5.40.5_n3_SvmFit0 $resample[1]

summary(Adult_TDA_KDE_5.40.5_n3_SvmFit0)

#vip(Adult_TDA_KDE_5.40.5_n3_SvmFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n3_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_KDE_5.40.5_n3_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n3_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n3_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n3_svm_cf0
ad_tda_kde_5.40.5_n3_svm_cf0 
ad_tda_kde_5.40.5_n3_svm_cf0$overall
ad_tda_kde_5.40.5_n3_svm_cf0_ov_acc<-ad_tda_kde_5.40.5_n3_svm_cf0$overall[1]
ad_tda_kde_5.40.5_n3_svm_cf0$byClass
ad_tda_kde_5.40.5_n3_svm_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n3_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_svm_n3_3_fold<-(ad_svm_fit_re - ad_tda_kde_5.40.5_n3_svm_fit_re)
diff_tda_kde_5.40.5_svm_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm_n3_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n3_3_fold_odds.left<-bst_tda_kde_5.40.5_svm.n3_3_fold$probLeft/bst_tda_kde_5.40.5_svm.n3_3_fold$probRight
bst_tda_kde_5.40.5_svm.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm_n3_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n3_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm_n3_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n3_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_svm_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n3_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm_n3_3_fold))
#bf_tda_kde_5.40.5_svm.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_svm_n3_3_fold))


### Test set diff
diff_tda_kde_5.40.5_svm.n3_test<-(svm_cf_ov_acc-ad_tda_kde_5.40.5_n3_svm_cf0_ov_acc)
diff_tda_kde_5.40.5_svm.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n3_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm.n3_test),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n3_test_odds.left<-bst_tda_kde_5.40.5_svm.n3_test$probLeft/bst_tda_kde_5.40.5_svm.n3_test$probRight
bst_tda_kde_5.40.5_svm.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n3_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm.n3_test),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n3_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm.n3_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n3_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_svm.n3_test))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n3_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm.n3_test)) #bf_tda_kde_5.40.5_svm.n3_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_svm.n3_test))

##Node4

Adult_TDA_KDE_5.40.5_n4_SvmFit0 <- train(as.factor(adult_df1) ~ ., data =  tda.m_kde_adult_5.40.5.n4.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_KDE_5.40.5_n4_SvmFit0
Adult_TDA_KDE_5.40.5_n4_SvmFit0$resample
ad_tda_kde_5.40.5_n4_svm_fit_re<-Adult_TDA_KDE_5.40.5_n4_SvmFit0 $resample[1]

summary(Adult_TDA_KDE_5.40.5_n4_SvmFit0)
#vip(Adult_TDA_KDE_5.40.5_n4_SvmFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_KDE_5.40.5_n4_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n4_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n4_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n4_svm_cf0
ad_tda_kde_5.40.5_n4_svm_cf0 
ad_tda_kde_5.40.5_n4_svm_cf0$overall
ad_tda_kde_5.40.5_n4_svm_cf0_ov_acc<-ad_tda_kde_5.40.5_n4_svm_cf0$overall[1]
ad_tda_kde_5.40.5_n4_svm_cf0$byClass
ad_tda_kde_5.40.5_n4_svm_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n4_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_svm_n4_3_fold<-(ad_svm_fit_re - ad_tda_kde_5.40.5_n4_svm_fit_re)
diff_tda_kde_5.40.5_svm_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm_n4_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n4_3_fold_odds.left<-bst_tda_kde_5.40.5_svm.n4_3_fold$probLeft/bst_tda_kde_5.40.5_svm.n4_3_fold$probRight
bst_tda_kde_5.40.5_svm.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm_n4_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n4_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm_n4_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n4_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_svm_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n4_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm_n4_3_fold))
#bf_tda_kde_5.40.5_svm.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_svm_n4_3_fold))


### Test set diff
diff_tda_kde_5.40.5_svm.n4_test<-(svm_cf_ov_acc-ad_tda_kde_5.40.5_n4_svm_cf0_ov_acc)
diff_tda_kde_5.40.5_svm.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n4_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm.n4_test),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n4_test_odds.left<-bst_tda_kde_5.40.5_svm.n4_test$probLeft/bst_tda_kde_5.40.5_svm.n4_test$probRight
bst_tda_kde_5.40.5_svm.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n4_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm.n4_test),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n4_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm.n4_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n4_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_svm.n4_test))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n4_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm.n4_test)) #bf_tda_kde_5.40.5_svm.n4_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_svm.n4_test))

##Node5

Adult_TDA_KDE_5.40.5_n5_SvmFit0 <- train(as.factor(adult_df1) ~ ., data =  tda.m_kde_adult_5.40.5.n3.vec, 
            	    Importance = T,
            	    method = 'svmRadial', 
                  trControl = fitControl,
				          tuneGrid = svmGrid, preProc = c('center','scale'),
				          metric='Accuracy')

Adult_TDA_KDE_5.40.5_n5_SvmFit0
Adult_TDA_KDE_5.40.5_n5_SvmFit0$resample
ad_tda_kde_5.40.5_n5_svm_fit_re<-Adult_TDA_KDE_5.40.5_n5_SvmFit0 $resample[1]

summary(Adult_TDA_KDE_5.40.5_n5_SvmFit0)
#vip(Adult_TDA_KDE_5.40.5_n5_SvmFit0,25) + ggtitle("Adult_TDA_KDE_5.40.5_n5_SvmFit TDA-Assited Svm")

# Predict outcome using Adult_TDA_KDE_5.40.5_n5_SvmFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n5_SvmFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n5_svm_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n5_svm_cf0
ad_tda_kde_5.40.5_n5_svm_cf0 
ad_tda_kde_5.40.5_n5_svm_cf0$overall
ad_tda_kde_5.40.5_n5_svm_cf0_ov_acc<-ad_tda_kde_5.40.5_n5_svm_cf0$overall[1]
ad_tda_kde_5.40.5_n5_svm_cf0$byClass
ad_tda_kde_5.40.5_n5_svm_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n5_svm_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_svm_n5_3_fold<-(ad_svm_fit_re - ad_tda_kde_5.40.5_n5_svm_fit_re)
diff_tda_kde_5.40.5_svm_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm_n5_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n5_3_fold_odds.left<-bst_tda_kde_5.40.5_svm.n5_3_fold$probLeft/bst_tda_kde_5.40.5_svm.n5_3_fold$probRight
bst_tda_kde_5.40.5_svm.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm_n5_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n5_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm_n5_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n5_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_svm_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n5_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm_n5_3_fold))
#bf_tda_kde_5.40.5_svm.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_svm_n5_3_fold))


### Test set diff
diff_tda_kde_5.40.5_svm.n5_test<-svm_cf_ov_acc-ad_tda_kde_5.40.5_n5_svm_cf0_ov_acc
diff_tda_kde_5.40.5_svm.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_svm.n5_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_svm.n5_test),-0.01,0.01)
bst_tda_kde_5.40.5_svm.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_svm.n5_test_odds.left<-bst_tda_kde_5.40.5_svm.n5_test$probLeft/bst_tda_kde_5.40.5_svm.n5_test$probRight
bst_tda_kde_5.40.5_svm.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_svm.n5_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_svm.n5_test),-0.01,0.01)
bsr_tda_kde_5.40.5_svm.n5_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_svm.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_svm.n5_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_svm.n5_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_svm.n5_test))

#BayesFactor
#bf_tda_kde_5.40.5_svm.n5_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_svm.n5_test)) #bf_tda_kde_5.40.5_svm.n5_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_svm.n4_test))


#Non-TDA-Assisted

nn1Grid<-expand.grid(size = c(2,3,5,7), decay = c(0.3,0.5,0.7))
#Neural Network 
adultNn1Fit <- train(as.factor(adult_df1) ~ ., data = adult.one_hot_df4Train, 
            			    Importance = T,
                      method = 'nnet', 
                      trControl = fitControl,
                      tuneGrid = nn1Grid,
                      metric='Accuracy')

adultNn1Fit
adultNn1Fit$resample
ad_nn1_fit_re<-adultNn1Fit$resample[1]

summary(adultNn1Fit)

vip(adultNn1Fit,25) + ggtitle("non-TDA-Assited NN")

# Predict outcome using model from training data based on testing data
predictions <- predict(adultNn1Fit, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
nn1_cf<-confusionMatrix(data=predictions, as.factor(adult.one_hot_df4Test$adult_df1))
nn1_cf
nn1_cf$overall
nn1_cf_ov_acc<-nn1_cf$overall[1]
nn1_cf$byClass 
nn1_cf_pre_rec_f1<-nn1_cf$byClass[5:7]

##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node1

#Neural Network 1
Adult_TDA_PC_5.40.5_n1_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n1.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_PC_5.40.5_n1_NN1Fit0
Adult_TDA_PC_5.40.5_n1_NN1Fit0$resample
ad_tda_pc_5.40.5_n1_nn1_fit_re<-Adult_TDA_PC_5.40.5_n1_NN1Fit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n1_NN1Fit0)

vip(Adult_TDA_PC_5.40.5_n1_NN1Fit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n1_NN1Fit TDA-Assited NN")


# Predict outcome using Adult_TDA_PC_5.40.5_n1_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n1_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n1_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n1_nn1_cf0
ad_tda_pc_5.40.5_n1_nn1_cf0 
ad_tda_pc_5.40.5_n1_nn1_cf0$overall
ad_tda_pc_5.40.5_n1_nn1_cf0_ov_acc<-ad_tda_pc_5.40.5_n1_nn1_cf0$overall[1]
ad_tda_pc_5.40.5_n1_nn1_cf0$byClass
ad_tda_pc_5.40.5_n1_nn1_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n1_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nn1_n1_3_fold<-(ad_nn1_fit_re - ad_tda_pc_5.40.5_n1_nn1_fit_re)
diff_tda_pca_5.40.5_nn1_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1_n1_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n1_3_fold_odds.left<-bst_tda_pca_5.40.5_nn1.n1_3_fold$probLeft/bst_tda_pca_5.40.5_nn1.n1_3_fold$probRight
bst_tda_pca_5.40.5_nn1.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1_n1_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n1_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1_n1_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n1_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nn1_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n1_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1_n1_3_fold))
#bf_tda_pca_5.40.5_nn1.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nn1_n1_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nn1.n1_test<-(nn1_cf_ov_acc - ad_tda_pc_5.40.5_n1_nn1_cf0_ov_acc)
diff_tda_pca_5.40.5_nn1.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n1_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1.n1_test),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n1_test_odds.left<-bst_tda_pca_5.40.5_nn1.n1_test$probLeft/bst_tda_pca_5.40.5_nn1.n1_test$probRight
bst_tda_pca_5.40.5_nn1.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n1_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1.n1_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n1_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1.n1_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n1_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nn1.n1_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n1_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1.n1_test)) #bf_tda_pca_5.40.5_nn1.n1_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nn1.n1_test))

##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node2

##Adult_TDA_PC_5.40.5_n2_NN1Fit0 <- nnet(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, size=2, range = 0.6,, type='class')

#Neural Network 1
Adult_TDA_PC_5.40.5_n2_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_PC_5.40.5_n2_NN1Fit0
Adult_TDA_PC_5.40.5_n2_NN1Fit0$resample
ad_tda_pc_5.40.5_n2_nn1_fit_re<-Adult_TDA_PC_5.40.5_n2_NN1Fit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n2_NN1Fit0)

vip(Adult_TDA_PC_5.40.5_n2_NN1Fit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n2_NN1Fit TDA-Assited NN")


# Predict outcome using Adult_TDA_PC_5.40.5_n2_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n2_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n2_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n2_nn1_cf0
ad_tda_pc_5.40.5_n2_nn1_cf0 
ad_tda_pc_5.40.5_n2_nn1_cf0$overall
ad_tda_pc_5.40.5_n2_nn1_cf0_ov_acc<-ad_tda_pc_5.40.5_n2_nn1_cf0$overall[1]
ad_tda_pc_5.40.5_n2_nn1_cf0$byClass
ad_tda_pc_5.40.5_n2_nn1_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n2_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nn1_n2_3_fold<-(ad_nn1_fit_re - ad_tda_pc_5.40.5_n2_nn1_fit_re)
diff_tda_pca_5.40.5_nn1_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1_n2_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n2_3_fold_odds.left<-bst_tda_pca_5.40.5_nn1.n2_3_fold$probLeft/bst_tda_pca_5.40.5_nn1.n2_3_fold$probRight
bst_tda_pca_5.40.5_nn1.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1_n2_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n2_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1_n2_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n2_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nn1_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n2_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1_n2_3_fold))
#bf_tda_pca_5.40.5_nn1.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nn1_n2_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nn1.n2_test<-(nn1_cf_ov_acc - ad_tda_pc_5.40.5_n2_nn1_cf0_ov_acc)
diff_tda_pca_5.40.5_nn1.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n2_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1.n2_test),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n2_test_odds.left<-bst_tda_pca_5.40.5_nn1.n2_test$probLeft/bst_tda_pca_5.40.5_nn1.n2_test$probRight
bst_tda_pca_5.40.5_nn1.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n2_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1.n2_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n2_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1.n2_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n2_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nn1.n2_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n2_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1.n2_test)) #bf_tda_pca_5.40.5_nn1.n2_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nn1.n2_test))


##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node3

#Neural Network 1
Adult_TDA_PC_5.40.5_n3_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n3.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_PC_5.40.5_n3_NN1Fit0
Adult_TDA_PC_5.40.5_n3_NN1Fit0$resample
ad_tda_pc_5.40.5_n3_nn1_fit_re<-Adult_TDA_PC_5.40.5_n3_NN1Fit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n3_NN1Fit0)

vip(Adult_TDA_PC_5.40.5_n3_NN1Fit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n3_NN1Fit TDA-Assited NN")

# Predict outcome using Adult_TDA_PC_5.40.5_n3_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n3_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n3_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n3_nn1_cf0
ad_tda_pc_5.40.5_n3_nn1_cf0 
ad_tda_pc_5.40.5_n3_nn1_cf0$overall
ad_tda_pc_5.40.5_n3_nn1_cf0_ov_acc<-ad_tda_pc_5.40.5_n3_nn1_cf0$overall[1]
ad_tda_pc_5.40.5_n3_nn1_cf0$byClass
ad_tda_pc_5.40.5_n3_nn1_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n3_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nn1_n3_3_fold<-(ad_nn1_fit_re - ad_tda_pc_5.40.5_n3_nn1_fit_re)
diff_tda_pca_5.40.5_nn1_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1_n3_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n3_3_fold_odds.left<-bst_tda_pca_5.40.5_nn1.n3_3_fold$probLeft/bst_tda_pca_5.40.5_nn1.n3_3_fold$probRight
bst_tda_pca_5.40.5_nn1.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1_n3_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n3_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1_n3_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n3_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nn1_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n3_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1_n3_3_fold))
#bf_tda_pca_5.40.5_nn1.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nn1_n3_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nn1.n3_test<-(nn1_cf_ov_acc - ad_tda_pc_5.40.5_n3_nn1_cf0_ov_acc)
diff_tda_pca_5.40.5_nn1.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n3_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1.n3_test),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n3_test_odds.left<-bst_tda_pca_5.40.5_nn1.n3_test$probLeft/bst_tda_pca_5.40.5_nn1.n3_test$probRight
bst_tda_pca_5.40.5_nn1.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n3_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1.n3_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n3_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1.n3_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n3_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nn1.n3_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n3_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1.n3_test)) #bf_tda_pca_5.40.5_nn1.n3_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nn1.n3_test))


##Node4

#Neural Network 1
Adult_TDA_PC_5.40.5_n4_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n4.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_PC_5.40.5_n4_NN1Fit0
Adult_TDA_PC_5.40.5_n4_NN1Fit0$resample
ad_tda_pc_5.40.5_n4_nn1_fit_re<-Adult_TDA_PC_5.40.5_n4_NN1Fit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n4_NN1Fit0)

vip(Adult_TDA_PC_5.40.5_n4_NN1Fit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n4_NN1Fit TDA-Assited NN")

# Predict outcome using Adult_TDA_PC_5.40.5_n4_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n4_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n4_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n4_nn1_cf0
ad_tda_pc_5.40.5_n4_nn1_cf0 
ad_tda_pc_5.40.5_n4_nn1_cf0$overall
ad_tda_pc_5.40.5_n4_nn1_cf0_ov_acc<-ad_tda_pc_5.40.5_n4_nn1_cf0$overall[1]
ad_tda_pc_5.40.5_n4_nn1_cf0$byClass
ad_tda_pc_5.40.5_n4_nn1_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n4_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nn1_n4_3_fold<-(ad_nn1_fit_re - ad_tda_pc_5.40.5_n4_nn1_fit_re)
diff_tda_pca_5.40.5_nn1_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1_n4_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n4_3_fold_odds.left<-bst_tda_pca_5.40.5_nn1.n4_3_fold$probLeft/bst_tda_pca_5.40.5_nn1.n4_3_fold$probRight
bst_tda_pca_5.40.5_nn1.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1_n4_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n4_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1_n4_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n4_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nn1_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n4_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1_n4_3_fold))
#bf_tda_pca_5.40.5_nn1.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nn1_n4_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nn1.n4_test<-(nn1_cf_ov_acc - ad_tda_pc_5.40.5_n4_nn1_cf0_ov_acc)
diff_tda_pca_5.40.5_nn1.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n4_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1.n4_test),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n4_test_odds.left<-bst_tda_pca_5.40.5_nn1.n4_test$probLeft/bst_tda_pca_5.40.5_nn1.n4_test$probRight
bst_tda_pca_5.40.5_nn1.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n4_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1.n4_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n4_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1.n4_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n4_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nn1.n4_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n4_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1.n4_test)) #bf_tda_pca_5.40.5_nn1.n4_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nn1.n4_test))


##Node5

#Neural Network 1
Adult_TDA_PC_5.40.5_n5_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n5.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_PC_5.40.5_n5_NN1Fit0
Adult_TDA_PC_5.40.5_n5_NN1Fit0$resample
ad_tda_pc_5.40.5_n5_nn1_fit_re<-Adult_TDA_PC_5.40.5_n5_NN1Fit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n5_NN1Fit0)

vip(Adult_TDA_PC_5.40.5_n5_NN1Fit0,25) + ggtitle("Adult_TDA_PCA_5.40.5_n5_NN1Fit TDA-Assited NN")

# Predict outcome using Adult_TDA_PC_5.40.5_n5_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n5_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n5_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n5_nn1_cf0
ad_tda_pc_5.40.5_n5_nn1_cf0 
ad_tda_pc_5.40.5_n5_nn1_cf0$overall
ad_tda_pc_5.40.5_n5_nn1_cf0_ov_acc<-ad_tda_pc_5.40.5_n5_nn1_cf0$overall[1]
ad_tda_pc_5.40.5_n5_nn1_cf0$byClass
ad_tda_pc_5.40.5_n5_nn1_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n5_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nn1_n5_3_fold<-(ad_nn1_fit_re - ad_tda_pc_5.40.5_n5_nn1_fit_re)
diff_tda_pca_5.40.5_nn1_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1_n5_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n5_3_fold_odds.left<-bst_tda_pca_5.40.5_nn1.n5_3_fold$probLeft/bst_tda_pca_5.40.5_nn1.n5_3_fold$probRight
bst_tda_pca_5.40.5_nn1.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1_n5_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n5_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1_n5_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n5_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nn1_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n5_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1_n5_3_fold))
#bf_tda_pca_5.40.5_nn1.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nn1_n5_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nn1.n5_test<-(nn1_cf_ov_acc - ad_tda_pc_5.40.5_n5_nn1_cf0_ov_acc)
diff_tda_pca_5.40.5_nn1.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nn1.n5_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nn1.n5_test),-0.01,0.01)
bst_tda_pca_5.40.5_nn1.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nn1.n5_test_odds.left<-bst_tda_pca_5.40.5_nn1.n5_test$probLeft/bst_tda_pca_5.40.5_nn1.n5_test$probRight
bst_tda_pca_5.40.5_nn1.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nn1.n5_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nn1.n5_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nn1.n5_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nn1.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nn1.n5_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nn1.n5_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nn1.n5_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nn1.n5_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nn1.n5_test)) #bf_tda_pca_5.40.5_nn1.n5_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nn1.n5_test))


##With TDA KDE filter 5 intervals, 50% overlap, 5 bins 
##Node1

#Neural Network 1
Adult_TDA_KDE_5.40.5_n1_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n1.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_KDE_5.40.5_n1_NN1Fit0
Adult_TDA_KDE_5.40.5_n1_NN1Fit0$resample
ad_tda_kde_5.40.5_n1_nn1_fit_re<-Adult_TDA_KDE_5.40.5_n1_NN1Fit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n1_NN1Fit0)

vip(Adult_TDA_KDE_5.40.5_n1_NN1Fit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n1_NN1Fit TDA-Assited NN")

# Predict outcome using Adult_TDA_KDE_5.40.5_n1_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n1_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n1_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n1_nn1_cf0
ad_tda_kde_5.40.5_n1_nn1_cf0 
ad_tda_kde_5.40.5_n1_nn1_cf0$overall
ad_tda_kde_5.40.5_n1_nn1_cf0_ov_acc<-ad_tda_kde_5.40.5_n1_nn1_cf0$overall[1]
ad_tda_kde_5.40.5_n1_nn1_cf0$byClass
ad_tda_kde_5.40.5_n1_nn1_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n1_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nn1_n1_3_fold<-(ad_nn1_fit_re - ad_tda_kde_5.40.5_n1_nn1_fit_re)
diff_tda_kde_5.40.5_nn1_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1_n1_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n1_3_fold_odds.left<-bst_tda_kde_5.40.5_nn1.n1_3_fold$probLeft/bst_tda_kde_5.40.5_nn1.n1_3_fold$probRight
bst_tda_kde_5.40.5_nn1.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1_n1_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n1_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1_n1_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n1_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nn1_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n1_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1_n1_3_fold))
#bf_tda_kde_5.40.5_nn1.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nn1_n1_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nn1.n1_test<-(nn1_cf_ov_acc - ad_tda_kde_5.40.5_n1_nn1_cf0_ov_acc)
diff_tda_kde_5.40.5_nn1.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n1_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1.n1_test),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n1_test_odds.left<-bst_tda_kde_5.40.5_nn1.n1_test$probLeft/bst_tda_kde_5.40.5_nn1.n1_test$probRight
bst_tda_kde_5.40.5_nn1.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n1_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1.n1_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n1_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1.n1_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n1_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nn1.n1_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n1_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1.n1_test)) #bf_tda_pca_5.40.5_nn1.n1_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nn1.n1_test))

##Node2

#Neural Network 1
Adult_TDA_KDE_5.40.5_n2_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n3.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_KDE_5.40.5_n2_NN1Fit0
Adult_TDA_KDE_5.40.5_n2_NN1Fit0$resample
ad_tda_kde_5.40.5_n2_nn1_fit_re<-Adult_TDA_KDE_5.40.5_n2_NN1Fit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n2_NN1Fit0)

vip(Adult_TDA_KDE_5.40.5_n2_NN1Fit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n2_NN1Fit TDA-Assited NN")

# Predict outcome using Adult_TDA_KDE_5.40.5_n2_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n2_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n2_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n2_nn1_cf0
ad_tda_kde_5.40.5_n2_nn1_cf0 
ad_tda_kde_5.40.5_n2_nn1_cf0$overall
ad_tda_kde_5.40.5_n2_nn1_cf0_ov_acc<-ad_tda_kde_5.40.5_n2_nn1_cf0$overall[1]
ad_tda_kde_5.40.5_n2_nn1_cf0$byClass
ad_tda_kde_5.40.5_n2_nn1_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n2_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nn1_n2_3_fold<-(ad_nn1_fit_re - ad_tda_kde_5.40.5_n2_nn1_fit_re)
diff_tda_kde_5.40.5_nn1_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1_n2_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n2_3_fold_odds.left<-bst_tda_kde_5.40.5_nn1.n2_3_fold$probLeft/bst_tda_kde_5.40.5_nn1.n2_3_fold$probRight
bst_tda_kde_5.40.5_nn1.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1_n2_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n2_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1_n2_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n2_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nn1_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n2_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1_n2_3_fold))
#bf_tda_kde_5.40.5_nn1.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nn1_n2_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nn1.n2_test<-(nn1_cf_ov_acc - ad_tda_kde_5.40.5_n2_nn1_cf0_ov_acc)
diff_tda_kde_5.40.5_nn1.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n2_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1.n2_test),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n2_test_odds.left<-bst_tda_kde_5.40.5_nn1.n2_test$probLeft/bst_tda_kde_5.40.5_nn1.n2_test$probRight
bst_tda_kde_5.40.5_nn1.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n2_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1.n2_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n2_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1.n2_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n2_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nn1.n2_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n2_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1.n2_test)) #bf_tda_pca_5.40.5_nn1.n2_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nn1.n2_test))

##Node3

#Neural Network 1
Adult_TDA_KDE_5.40.5_n3_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n3.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_KDE_5.40.5_n3_NN1Fit0
Adult_TDA_KDE_5.40.5_n3_NN1Fit0$resample
ad_tda_kde_5.40.5_n3_nn1_fit_re<-Adult_TDA_KDE_5.40.5_n3_NN1Fit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n3_NN1Fit0)

vip(Adult_TDA_KDE_5.40.5_n3_NN1Fit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n3_NN1Fit TDA-Assited NN")

# Predict outcome using Adult_TDA_KDE_5.40.5_n3_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n3_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n3_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n3_nn1_cf0
ad_tda_kde_5.40.5_n3_nn1_cf0 
ad_tda_kde_5.40.5_n3_nn1_cf0$overall
ad_tda_kde_5.40.5_n3_nn1_cf0_ov_acc<-ad_tda_kde_5.40.5_n3_nn1_cf0$overall[1]
ad_tda_kde_5.40.5_n3_nn1_cf0$byClass
ad_tda_kde_5.40.5_n3_nn1_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n3_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nn1_n3_3_fold<-(ad_nn1_fit_re - ad_tda_kde_5.40.5_n3_nn1_fit_re)
diff_tda_kde_5.40.5_nn1_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1_n3_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n3_3_fold_odds.left<-bst_tda_kde_5.40.5_nn1.n3_3_fold$probLeft/bst_tda_kde_5.40.5_nn1.n3_3_fold$probRight
bst_tda_kde_5.40.5_nn1.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1_n3_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n3_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1_n3_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n3_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nn1_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n3_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1_n3_3_fold))
#bf_tda_kde_5.40.5_nn1.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nn1_n3_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nn1.n3_test<-(nn1_cf_ov_acc - ad_tda_kde_5.40.5_n3_nn1_cf0_ov_acc)
diff_tda_kde_5.40.5_nn1.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n3_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1.n3_test),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n3_test_odds.left<-bst_tda_kde_5.40.5_nn1.n3_test$probLeft/bst_tda_kde_5.40.5_nn1.n3_test$probRight
bst_tda_kde_5.40.5_nn1.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n3_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1.n3_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n3_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1.n3_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n3_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nn1.n3_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n3_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1.n3_test)) #bf_tda_pca_5.40.5_nn1.n3_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nn1.n3_test))

##Node4

#Neural Network 1
Adult_TDA_KDE_5.40.5_n4_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n4.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_KDE_5.40.5_n4_NN1Fit0
Adult_TDA_KDE_5.40.5_n4_NN1Fit0$resample
ad_tda_kde_5.40.5_n4_nn1_fit_re<-Adult_TDA_KDE_5.40.5_n4_NN1Fit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n4_NN1Fit0)

vip(Adult_TDA_KDE_5.40.5_n4_NN1Fit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n4_NN1Fit TDA-Assited NN")
 

# Predict outcome using Adult_TDA_KDE_5.40.5_n4_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n4_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n4_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n4_nn1_cf0
ad_tda_kde_5.40.5_n4_nn1_cf0 
ad_tda_kde_5.40.5_n4_nn1_cf0$overall
ad_tda_kde_5.40.5_n4_nn1_cf0_ov_acc<-ad_tda_kde_5.40.5_n4_nn1_cf0$overall[1]
ad_tda_kde_5.40.5_n4_nn1_cf0$byClass
ad_tda_kde_5.40.5_n4_nn1_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n4_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nn1_n4_3_fold<-(ad_nn1_fit_re - ad_tda_kde_5.40.5_n4_nn1_fit_re)
diff_tda_kde_5.40.5_nn1_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1_n4_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n4_3_fold_odds.left<-bst_tda_kde_5.40.5_nn1.n4_3_fold$probLeft/bst_tda_kde_5.40.5_nn1.n4_3_fold$probRight
bst_tda_kde_5.40.5_nn1.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1_n4_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n4_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1_n4_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n4_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nn1_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n4_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1_n4_3_fold))
#bf_tda_kde_5.40.5_nn1.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nn1_n4_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nn1.n4_test<-(nn1_cf_ov_acc - ad_tda_kde_5.40.5_n4_nn1_cf0_ov_acc)
diff_tda_kde_5.40.5_nn1.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n4_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1.n4_test),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n4_test_odds.left<-bst_tda_kde_5.40.5_nn1.n4_test$probLeft/bst_tda_kde_5.40.5_nn1.n4_test$probRight
bst_tda_kde_5.40.5_nn1.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n4_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1.n4_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n4_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1.n4_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n4_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nn1.n4_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n4_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1.n4_test)) #bf_tda_pca_5.40.5_nn1.n4_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nn1.n4_test))

##Node5

#Neural Network 1

Adult_TDA_KDE_5.40.5_n5_NN1Fit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n5.vec, 
			               Importance = T,
                     method = 'nnet', 
                     trControl = fitControl,
                     tuneGrid = nn1Grid,
                     metric='Accuracy')

Adult_TDA_KDE_5.40.5_n5_NN1Fit0
Adult_TDA_KDE_5.40.5_n5_NN1Fit0$resample
ad_tda_kde_5.40.5_n5_nn1_fit_re<-Adult_TDA_KDE_5.40.5_n5_NN1Fit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n5_NN1Fit0)
vip(Adult_TDA_KDE_5.40.5_n5_NN1Fit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n5_NN1Fit TDA-Assited NN")


# Predict outcome using Adult_TDA_KDE_5.40.5_n5_NN1Fit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n5_NN1Fit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n5_nn1_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n5_nn1_cf0
ad_tda_kde_5.40.5_n5_nn1_cf0 
ad_tda_kde_5.40.5_n5_nn1_cf0$overall
ad_tda_kde_5.40.5_n5_nn1_cf0_ov_acc<-ad_tda_kde_5.40.5_n5_nn1_cf0$overall[1]
ad_tda_kde_5.40.5_n5_nn1_cf0$byClass
ad_tda_kde_5.40.5_n5_nn1_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n5_nn1_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nn1_n5_3_fold<-(ad_nn1_fit_re - ad_tda_kde_5.40.5_n5_nn1_fit_re)
diff_tda_kde_5.40.5_nn1_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1_n5_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n5_3_fold_odds.left<-bst_tda_kde_5.40.5_nn1.n5_3_fold$probLeft/bst_tda_kde_5.40.5_nn1.n5_3_fold$probRight
bst_tda_kde_5.40.5_nn1.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1_n5_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n5_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1_n5_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n5_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nn1_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n5_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1_n5_3_fold))
#bf_tda_kde_5.40.5_nn1.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nn1_n5_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nn1.n5_test<-(nn1_cf_ov_acc - ad_tda_kde_5.40.5_n5_nn1_cf0_ov_acc)
diff_tda_kde_5.40.5_nn1.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nn1.n5_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nn1.n5_test),-0.01,0.01)
bst_tda_kde_5.40.5_nn1.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nn1.n5_test_odds.left<-bst_tda_kde_5.40.5_nn1.n5_test$probLeft/bst_tda_kde_5.40.5_nn1.n5_test$probRight
bst_tda_kde_5.40.5_nn1.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nn1.n4_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nn1.n4_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nn1.n4_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nn1.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nn1.n5_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nn1.n5_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nn1.n5_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nn1.n5_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nn1.n5_test)) #bf_tda_pca_5.40.5_nn1.n5_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nn1.n5_test)) 


##Logistic Regression 

adultLrFit <- train(as.factor(adult_df1) ~ ., 
                 data = adult.one_hot_df4Train, 
                 family = 'binomial',
			    method = 'glm', 
                 trControl = fitControl,
			    metric='Accuracy')
adultLrFit
adultLrFit$resample
ad_lr_fit_re<-adultLrFit$resample[1]

summary(adultLrFit)

vip(adultLrFit,25) + ggtitle('non-TDA-Assisted LR')

# Predict outcome using model from training data based on testing data
predictions <- predict(adultLrFit, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
lr_cf<-confusionMatrix(data=predictions, as.factor(adult.one_hot_df4Test$adult_df1))
lr_cf
lr_cf$overall
lr_cf_ov_acc<-lr_cf$overall[1]
lr_cf$byClass
lr_cf_pre_rec_f1<-lr_cf$byClass[5:7]


##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node1

Adult_TDA_PC_5.40.5_n1_LrFit0 <- glm(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n1.vec, family = 'binomial')

Adult_TDA_PC_5.40.5_n1_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_adult_5.40.5.n1.vec, 
                    family = 'binomial',
			              method = 'glm', 
                    trControl = fitControl,
			              metric='Accuracy')

Adult_TDA_PC_5.40.5_n1_LrFit0
Adult_TDA_PC_5.40.5_n1_LrFit0$resample
ad_tda_pc_5.40.5_n1_lr_fit_re<-Adult_TDA_PC_5.40.5_n1_LrFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n1_LrFit0)

vip(Adult_TDA_PC_5.40.5_n1_LrFit0,50) + ggtitle("Adult_TDA_PCA_5.40.5_n1_Lr1Fit TDA-Assited LR")
# Predict outcome using Adult_TDA_PC_5.40.5_n1_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n1_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n1_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n1_lr_cf0
ad_tda_pc_5.40.5_n1_lr_cf0 
ad_tda_pc_5.40.5_n1_lr_cf0$overall
ad_tda_pc_5.40.5_n1_lr_cf0_ov_acc<-ad_tda_pc_5.40.5_n1_lr_cf0$overall[1]
ad_tda_pc_5.40.5_n1_lr_cf0$byClass
ad_tda_pc_5.40.5_n1_lr_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n1_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted LR vs. tda-assisted LR classifiers

### 3-fold diff

diff_tda_pca_5.40.5_lr_n1_3_fold<-(ad_lr_fit_re - ad_tda_pc_5.40.5_n1_lr_fit_re)
diff_tda_pca_5.40.5_lr_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr_n1_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n1_3_fold_odds.left<-bst_tda_pca_5.40.5_lr.n1_3_fold$probLeft/bst_tda_pca_5.40.5_lr.n1_3_fold$probRight
bst_tda_pca_5.40.5_lr.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr_n1_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n1_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr_n1_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n1_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_lr_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n1_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr_n1_3_fold))
#bf_tda_pca_5.40.5_lr.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_lr_n1_3_fold))


### Test set diff
diff_tda_pca_5.40.5_lr.n1_test<-(lr_cf_ov_acc - ad_tda_pc_5.40.5_n1_lr_cf0_ov_acc)
diff_tda_pca_5.40.5_lr.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n1_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr.n1_test),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n1_test_odds.left<-bst_tda_pca_5.40.5_lr.n1_test$probLeft/bst_tda_pca_5.40.5_lr.n1_test$probRight
bst_tda_pca_5.40.5_lr.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n1_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr.n1_test),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n1_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr.n1_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n1_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_lr.n1_test)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n1_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr.n1_test)) #bf_tda_pca_5.40.5_lr.n1_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_lr.n1_test))

##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node2

Adult_TDA_PC_5.40.5_n2_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_adult_5.40.5.n2.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_PC_5.40.5_n2_LrFit0
Adult_TDA_PC_5.40.5_n2_LrFit0$resample
ad_tda_pc_5.40.5_n2_lr_fit_re<-Adult_TDA_PC_5.40.5_n2_LrFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n2_LrFit0)

vip(Adult_TDA_PC_5.40.5_n2_LrFit0,50) + ggtitle("Adult_TDA_PCA_5.40.5_n2_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_PC_5.40.5_n2_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n2_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n2_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n2_lr_cf0
ad_tda_pc_5.40.5_n2_lr_cf0 
ad_tda_pc_5.40.5_n2_lr_cf0$overall
ad_tda_pc_5.40.5_n2_lr_cf0_ov_acc<-ad_tda_pc_5.40.5_n2_lr_cf0$overall[1]
ad_tda_pc_5.40.5_n2_lr_cf0$byClass
ad_tda_pc_5.40.5_n2_lr_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n2_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted LR vs. tda-assisted LR classifiers

### 3-fold diff

diff_tda_pca_5.40.5_lr_n2_3_fold<-(ad_lr_fit_re - ad_tda_pc_5.40.5_n2_lr_fit_re)
diff_tda_pca_5.40.5_lr_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr_n2_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n2_3_fold_odds.left<-bst_tda_pca_5.40.5_lr.n2_3_fold$probLeft/bst_tda_pca_5.40.5_lr.n2_3_fold$probRight
bst_tda_pca_5.40.5_lr.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr_n2_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n2_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr_n2_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n2_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_lr_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n2_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr_n2_3_fold))
#bf_tda_pca_5.40.5_lr.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_lr_n2_3_fold))


### Test set diff
diff_tda_pca_5.40.5_lr.n2_test<-(lr_cf_ov_acc - ad_tda_pc_5.40.5_n2_lr_cf0_ov_acc)
diff_tda_pca_5.40.5_lr.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n2_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr.n2_test),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n2_test_odds.left<-bst_tda_pca_5.40.5_lr.n2_test$probLeft/bst_tda_pca_5.40.5_lr.n2_test$probRight
bst_tda_pca_5.40.5_lr.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n2_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr.n2_test),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n2_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr.n2_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n2_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_lr.n2_test)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n2_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr.n2_test)) #bf_tda_pca_5.40.5_lr.n2_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_lr.n2_test))

##Node3

Adult_TDA_PC_5.40.5_n3_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_adult_5.40.5.n3.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_PC_5.40.5_n3_LrFit0
Adult_TDA_PC_5.40.5_n3_LrFit0$resample
ad_tda_pc_5.40.5_n3_lr_fit_re<-Adult_TDA_PC_5.40.5_n2_LrFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n3_LrFit0)

vip(Adult_TDA_PC_5.40.5_n3_LrFit0,50) + ggtitle("Adult_TDA_PCA_5.40.5_n3_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_PC_5.40.5_n3_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n3_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n3_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n3_lr_cf0
ad_tda_pc_5.40.5_n3_lr_cf0 
ad_tda_pc_5.40.5_n3_lr_cf0$overall
ad_tda_pc_5.40.5_n3_lr_cf0_ov_acc<-ad_tda_pc_5.40.5_n3_lr_cf0$overall[1]
ad_tda_pc_5.40.5_n3_lr_cf0$byClass
ad_tda_pc_5.40.5_n3_lr_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n3_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted LR vs. tda-assisted LR classifiers

### 3-fold diff

diff_tda_pca_5.40.5_lr_n3_3_fold<-(ad_lr_fit_re - ad_tda_pc_5.40.5_n3_lr_fit_re)
diff_tda_pca_5.40.5_lr_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr_n3_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n3_3_fold_odds.left<-bst_tda_pca_5.40.5_lr.n3_3_fold$probLeft/bst_tda_pca_5.40.5_lr.n3_3_fold$probRight
bst_tda_pca_5.40.5_lr.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr_n3_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n3_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr_n3_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n3_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_lr_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n3_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr_n3_3_fold))
#bf_tda_pca_5.40.5_lr.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_lr_n3_3_fold))


### Test set diff
diff_tda_pca_5.40.5_lr.n3_test<-(lr_cf_ov_acc - ad_tda_pc_5.40.5_n3_lr_cf0_ov_acc)
diff_tda_pca_5.40.5_lr.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n3_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr.n3_test),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n3_test_odds.left<-bst_tda_pca_5.40.5_lr.n3_test$probLeft/bst_tda_pca_5.40.5_lr.n3_test$probRight
bst_tda_pca_5.40.5_lr.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n3_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr.n3_test),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n3_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr.n3_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n3_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_lr.n3_test)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n3_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr.n3_test)) #bf_tda_pca_5.40.5_lr.n3_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_lr.n3_test))

##Node4

Adult_TDA_PC_5.40.5_n4_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_adult_5.40.5.n4.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_PC_5.40.5_n4_LrFit0
Adult_TDA_PC_5.40.5_n4_LrFit0$resample
ad_tda_pc_5.40.5_n4_lr_fit_re<-Adult_TDA_PC_5.40.5_n4_LrFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n4_LrFit0)

vip(Adult_TDA_PC_5.40.5_n4_LrFit0,50) + ggtitle("Adult_TDA_PCA_5.40.5_n4_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_PC_5.40.5_n4_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n4_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n4_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n4_lr_cf0
ad_tda_pc_5.40.5_n4_lr_cf0 
ad_tda_pc_5.40.5_n4_lr_cf0$overall
ad_tda_pc_5.40.5_n4_lr_cf0_ov_acc<-ad_tda_pc_5.40.5_n4_lr_cf0$overall[1]
ad_tda_pc_5.40.5_n4_lr_cf0$byClass
ad_tda_pc_5.40.5_n4_lr_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n4_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted LR vs. tda-assisted LR classifiers

### 3-fold diff

diff_tda_pca_5.40.5_lr_n4_3_fold<-(ad_lr_fit_re - ad_tda_pc_5.40.5_n4_lr_fit_re)
diff_tda_pca_5.40.5_lr_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr_n4_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n4_3_fold_odds.left<-bst_tda_pca_5.40.5_lr.n4_3_fold$probLeft/bst_tda_pca_5.40.5_lr.n4_3_fold$probRight
bst_tda_pca_5.40.5_lr.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr_n4_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n4_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr_n4_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n4_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_lr_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n4_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr_n4_3_fold))
#bf_tda_pca_5.40.5_lr.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_lr_n4_3_fold))


### Test set diff
diff_tda_pca_5.40.5_lr.n4_test<-(lr_cf_ov_acc - ad_tda_pc_5.40.5_n4_lr_cf0_ov_acc)
diff_tda_pca_5.40.5_lr.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n4_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr.n4_test),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n4_test_odds.left<-bst_tda_pca_5.40.5_lr.n4_test$probLeft/bst_tda_pca_5.40.5_lr.n4_test$probRight
bst_tda_pca_5.40.5_lr.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n4_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr.n4_test),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n4_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr.n4_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n4_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_lr.n4_test)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n4_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr.n4_test)) #bf_tda_pca_5.40.5_lr.n4_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_lr.n4_test))

##Node5

Adult_TDA_PC_5.40.5_n5_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_adult_5.40.5.n5.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_PC_5.40.5_n5_LrFit0
Adult_TDA_PC_5.40.5_n5_LrFit0$resample
ad_tda_pc_5.40.5_n5_lr_fit_re<-Adult_TDA_PC_5.40.5_n5_LrFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n5_LrFit0)

vip(Adult_TDA_PC_5.40.5_n5_LrFit0,50) + ggtitle("Adult_TDA_PCA_5.40.5_n5_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_PC_5.40.5_n5_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n5_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n5_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n5_lr_cf0
ad_tda_pc_5.40.5_n5_lr_cf0 
ad_tda_pc_5.40.5_n5_lr_cf0$overall
ad_tda_pc_5.40.5_n5_lr_cf0_ov_acc<-ad_tda_pc_5.40.5_n5_lr_cf0$overall[1]
ad_tda_pc_5.40.5_n5_lr_cf0$byClass
ad_tda_pc_5.40.5_n5_lr_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n5_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted LR vs. tda-assisted LR classifiers

### 3-fold diff

diff_tda_pca_5.40.5_lr_n5_3_fold<-(ad_lr_fit_re - ad_tda_pc_5.40.5_n5_lr_fit_re)
diff_tda_pca_5.40.5_lr_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr_n5_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n5_3_fold_odds.left<-bst_tda_pca_5.40.5_lr.n5_3_fold$probLeft/bst_tda_pca_5.40.5_lr.n5_3_fold$probRight
bst_tda_pca_5.40.5_lr.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr_n5_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n5_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr_n5_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n5_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_lr_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n5_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr_n5_3_fold))
#bf_tda_pca_5.40.5_lr.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_lr_n5_3_fold))


### Test set diff
diff_tda_pca_5.40.5_lr.n5_test<-(lr_cf_ov_acc - ad_tda_pc_5.40.5_n5_lr_cf0_ov_acc)
diff_tda_pca_5.40.5_lr.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_lr.n5_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_lr.n5_test),-0.01,0.01)
bst_tda_pca_5.40.5_lr.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_lr.n5_test_odds.left<-bst_tda_pca_5.40.5_lr.n5_test$probLeft/bst_tda_pca_5.40.5_lr.n5_test$probRight
bst_tda_pca_5.40.5_lr.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_lr.n5_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_lr.n5_test),-0.01,0.01)
bsr_tda_pca_5.40.5_lr.n5_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_lr.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_lr.n5_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_lr.n5_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_lr.n5_test)))

#BayesFactor
#bf_tda_pca_5.40.5_lr.n5_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_lr.n5_test)) #bf_tda_pca_5.40.5_lr.n5_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_lr.n5_test))


##With TDA KDE filter 5 intervals, 50% overlap, 5 bins 
##Node1


Adult_TDA_KDE_5.40.5_n1_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_kde_adult_5.40.5.n1.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n1_LrFit0
Adult_TDA_KDE_5.40.5_n1_LrFit0$resample
ad_tda_kde_5.40.5_n1_lr_fit_re<-Adult_TDA_KDE_5.40.5_n1_LrFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n1_LrFit0)

vip(Adult_TDA_KDE_5.40.5_n1_LrFit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n1_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_KDE_5.40.5_n1_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n1_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n1_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n1_lr_cf0
ad_tda_kde_5.40.5_n1_lr_cf0 
ad_tda_kde_5.40.5_n1_lr_cf0$overall
ad_tda_kde_5.40.5_n1_lr_cf0_ov_acc<-ad_tda_kde_5.40.5_n1_lr_cf0$overall[1]
ad_tda_kde_5.40.5_n1_lr_cf0$byClass
ad_tda_kde_5.40.5_n1_lr_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n1_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_lr_n1_3_fold<-(ad_lr_fit_re - ad_tda_kde_5.40.5_n1_lr_fit_re)
diff_tda_kde_5.40.5_lr_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr_n1_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n1_3_fold_odds.left<-bst_tda_kde_5.40.5_lr.n1_3_fold$probLeft/bst_tda_kde_5.40.5_lr.n1_3_fold$probRight
bst_tda_kde_5.40.5_lr.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr_n1_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n1_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr_n1_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n1_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_lr_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n1_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr_n1_3_fold))
#bf_tda_kde_5.40.5_lr.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_lr_n1_3_fold))


### Test set diff
diff_tda_kde_5.40.5_lr.n1_test<-(lr_cf_ov_acc - ad_tda_kde_5.40.5_n1_lr_cf0_ov_acc)
diff_tda_kde_5.40.5_lr.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n1_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr.n1_test),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n1_test_odds.left<-bst_tda_kde_5.40.5_lr.n1_test$probLeft/bst_tda_kde_5.40.5_lr.n1_test$probRight
bst_tda_kde_5.40.5_lr.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n1_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr.n1_test),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n1_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr.n1_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n1_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_lr.n1_test)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n1_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr.n1_test)) #bf_tda_pca_5.40.5_lr.n1_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_lr.n1_test))


##With TDA KDE filter 5 intervals, 50% overlap, 5 bins 
##Node2

Adult_TDA_KDE_5.40.5_n2_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_kde_adult_5.40.5.n2.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n2_LrFit0
Adult_TDA_KDE_5.40.5_n2_LrFit0$resample
ad_tda_kde_5.40.5_n2_lr_fit_re<-Adult_TDA_KDE_5.40.5_n2_LrFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n2_LrFit0)

vip(Adult_TDA_KDE_5.40.5_n2_LrFit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n2_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_KDE_5.40.5_n2_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n2_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n2_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n2_lr_cf0
ad_tda_kde_5.40.5_n2_lr_cf0 
ad_tda_kde_5.40.5_n2_lr_cf0$overall
ad_tda_kde_5.40.5_n2_lr_cf0_ov_acc<-ad_tda_kde_5.40.5_n2_lr_cf0$overall[1]
ad_tda_kde_5.40.5_n2_lr_cf0$byClass
ad_tda_kde_5.40.5_n2_lr_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n2_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_lr_n2_3_fold<-(ad_lr_fit_re - ad_tda_kde_5.40.5_n2_lr_fit_re)
diff_tda_kde_5.40.5_lr_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr_n2_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n2_3_fold_odds.left<-bst_tda_kde_5.40.5_lr.n2_3_fold$probLeft/bst_tda_kde_5.40.5_lr.n2_3_fold$probRight
bst_tda_kde_5.40.5_lr.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr_n2_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n2_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr_n2_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n2_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_lr_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n2_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr_n2_3_fold))
#bf_tda_kde_5.40.5_lr.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_lr_n2_3_fold))


### Test set diff
diff_tda_kde_5.40.5_lr.n2_test<-(lr_cf_ov_acc - ad_tda_kde_5.40.5_n2_lr_cf0_ov_acc)
diff_tda_kde_5.40.5_lr.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n2_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr.n2_test),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n2_test_odds.left<-bst_tda_kde_5.40.5_lr.n2_test$probLeft/bst_tda_kde_5.40.5_lr.n2_test$probRight
bst_tda_kde_5.40.5_lr.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n2_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr.n2_test),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n2_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr.n2_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n2_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_lr.n2_test)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n2_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr.n2_test)) #bf_tda_pca_5.40.5_lr.n2_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_lr.n2_test))

##Node3

Adult_TDA_KDE_5.40.5_n3_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_kde_adult_5.40.5.n3.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n3_LrFit0
Adult_TDA_KDE_5.40.5_n3_LrFit0$resample
ad_tda_kde_5.40.5_n3_lr_fit_re<-Adult_TDA_KDE_5.40.5_n2_LrFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n3_LrFit0)

vip(Adult_TDA_KDE_5.40.5_n3_LrFit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n3_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_KDE_5.40.5_n3_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n3_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n3_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n3_lr_cf0
ad_tda_kde_5.40.5_n3_lr_cf0 
ad_tda_kde_5.40.5_n3_lr_cf0$overall
ad_tda_kde_5.40.5_n3_lr_cf0_ov_acc<-ad_tda_kde_5.40.5_n3_lr_cf0$overall[1]
ad_tda_kde_5.40.5_n3_lr_cf0$byClass
ad_tda_kde_5.40.5_n3_lr_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n3_lr_cf0$byClass[5:7]


###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_lr_n3_3_fold<-(ad_lr_fit_re - ad_tda_kde_5.40.5_n3_lr_fit_re)
diff_tda_kde_5.40.5_lr_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr_n3_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n3_3_fold_odds.left<-bst_tda_kde_5.40.5_lr.n3_3_fold$probLeft/bst_tda_kde_5.40.5_lr.n3_3_fold$probRight
bst_tda_kde_5.40.5_lr.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr_n3_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n3_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr_n3_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n3_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_lr_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n3_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr_n3_3_fold))
#bf_tda_kde_5.40.5_lr.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_lr_n3_3_fold))


### Test set diff
diff_tda_kde_5.40.5_lr.n3_test<-(lr_cf_ov_acc - ad_tda_kde_5.40.5_n3_lr_cf0_ov_acc)
diff_tda_kde_5.40.5_lr.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n3_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr.n3_test),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n3_test_odds.left<-bst_tda_kde_5.40.5_lr.n3_test$probLeft/bst_tda_kde_5.40.5_lr.n3_test$probRight
bst_tda_kde_5.40.5_lr.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n2_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr.n2_test),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n2_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr.n3_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n3_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_lr.n3_test)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n3_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr.n3_test)) #bf_tda_pca_5.40.5_lr.n3_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_lr.n3_test))

##Node4

Adult_TDA_KDE_5.40.5_n4_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_kde_adult_5.40.5.n4.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n4_LrFit0
Adult_TDA_KDE_5.40.5_n4_LrFit0$resample
ad_tda_kde_5.40.5_n4_lr_fit_re<-Adult_TDA_KDE_5.40.5_n4_LrFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n4_LrFit0)

vip(Adult_TDA_KDE_5.40.5_n4_LrFit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n4_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_KDE_5.40.5_n4_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n4_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n4_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n4_lr_cf0
ad_tda_kde_5.40.5_n4_lr_cf0 
ad_tda_kde_5.40.5_n4_lr_cf0$overall
ad_tda_kde_5.40.5_n4_lr_cf0_ov_acc<-ad_tda_kde_5.40.5_n4_lr_cf0$overall[1]
ad_tda_kde_5.40.5_n4_lr_cf0$byClass
ad_tda_kde_5.40.5_n4_lr_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n4_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_lr_n4_3_fold<-(ad_lr_fit_re - ad_tda_kde_5.40.5_n4_lr_fit_re)
diff_tda_kde_5.40.5_lr_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr_n4_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n4_3_fold_odds.left<-bst_tda_kde_5.40.5_lr.n4_3_fold$probLeft/bst_tda_kde_5.40.5_lr.n4_3_fold$probRight
bst_tda_kde_5.40.5_lr.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr_n4_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n4_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr_n4_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n4_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_lr_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n4_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr_n4_3_fold))
#bf_tda_kde_5.40.5_lr.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_lr_n4_3_fold))


### Test set diff
diff_tda_kde_5.40.5_lr.n4_test<-(lr_cf_ov_acc - ad_tda_kde_5.40.5_n4_lr_cf0_ov_acc)
diff_tda_kde_5.40.5_lr.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n4_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr.n4_test),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n4_test_odds.left<-bst_tda_kde_5.40.5_lr.n4_test$probLeft/bst_tda_kde_5.40.5_lr.n4_test$probRight
bst_tda_kde_5.40.5_lr.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n4_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr.n4_test),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n4_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr.n4_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n4_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_lr.n4_test)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n4_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr.n4_test)) #bf_tda_pca_5.40.5_lr.n4_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_lr.n4_test))

##Node5

Adult_TDA_KDE_5.40.5_n5_LrFit0 <- train(as.factor(adult_df1) ~ ., 
                 data = tda.m_kde_adult_5.40.5.n5.vec, 
                      family = 'binomial',
			                method = 'glm', 
                      trControl = fitControl,
			                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n5_LrFit0
Adult_TDA_KDE_5.40.5_n5_LrFit0$resample
ad_tda_kde_5.40.5_n5_lr_fit_re<-Adult_TDA_KDE_5.40.5_n5_LrFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n5_LrFit0)

vip(Adult_TDA_KDE_5.40.5_n5_LrFit0,50) + ggtitle("Adult_TDA_KDE_5.40.5_n5_Lr1Fit TDA-Assited LR")

# Predict outcome using Adult_TDA_KDE_5.40.5_n5_LrFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n5_LrFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n5_lr_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n5_lr_cf0
ad_tda_kde_5.40.5_n5_lr_cf0 
ad_tda_kde_5.40.5_n5_lr_cf0$overall
ad_tda_kde_5.40.5_n5_lr_cf0_ov_acc<-ad_tda_kde_5.40.5_n5_lr_cf0$overall[1]
ad_tda_kde_5.40.5_n5_lr_cf0$byClass
ad_tda_kde_5.40.5_n5_lr_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n5_lr_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_lr_n5_3_fold<-(ad_lr_fit_re - ad_tda_kde_5.40.5_n5_lr_fit_re)
diff_tda_kde_5.40.5_lr_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr_n5_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n5_3_fold_odds.left<-bst_tda_kde_5.40.5_lr.n5_3_fold$probLeft/bst_tda_kde_5.40.5_lr.n5_3_fold$probRight
bst_tda_kde_5.40.5_lr.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr_n5_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n5_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr_n5_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n5_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_lr_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n5_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr_n5_3_fold))
#bf_tda_kde_5.40.5_lr.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_lr_n5_3_fold))


### Test set diff
diff_tda_kde_5.40.5_lr.n5_test<-(lr_cf_ov_acc - ad_tda_kde_5.40.5_n5_lr_cf0_ov_acc)
diff_tda_kde_5.40.5_lr.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_lr.n5_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_lr.n5_test),-0.01,0.01)
bst_tda_kde_5.40.5_lr.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_lr.n5_test_odds.left<-bst_tda_kde_5.40.5_lr.n5_test$probLeft/bst_tda_kde_5.40.5_lr.n5_test$probRight
bst_tda_kde_5.40.5_lr.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_lr.n5_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_lr.n5_test),-0.01,0.01)
bsr_tda_kde_5.40.5_lr.n5_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_lr.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_lr.n5_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_lr.n5_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_lr.n5_test)))

#BayesFactor
#bf_tda_kde_5.40.5_lr.n5_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_lr.n5_test)) #bf_tda_pca_5.40.5_lr.n5_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_lr.n5_test))


#naiveBayes 
adultNbFit <- train(as.factor(adult_df1) ~ ., data = adult.one_hot_df4Train, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

adultNbFit
adultNbFit$resample
ad_nb_fit_re<-adultNbFit$resample[1]

summary(adultNbFit)

#varImp (adultNbFit)



# Predict outcome using model from training data based on testing data
predictions <- predict(adultNbFit, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
nb_cf<-confusionMatrix(data=predictions, as.factor(adult.one_hot_df4Test$adult_df1))
nb_cf
nb_cf$overall
nb_cf_ov_acc<-nb_cf$overall[1]
nb_cf$byClass
nb_cf_pre_rec_f1<-nb_cf$byClass[5:7]


##With TDA PCA filter 5 intervals, 50% overlap, 5 bins 
##Node1

Adult_TDA_PC_5.40.5_n1_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n1.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_PC_5.40.5_n1_NbFit0
Adult_TDA_PC_5.40.5_n1_NbFit0$resample
ad_tda_pc_5.40.5_n1_nb_fit_re<-Adult_TDA_PC_5.40.5_n1_NbFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n1_NbFit0)

# Predict outcome using Adult_TDA_PC_5.40.5_n1_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n1_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n1_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n1_nb_cf0
ad_tda_pc_5.40.5_n1_nb_cf0 
ad_tda_pc_5.40.5_n1_nb_cf0$overall
ad_tda_pc_5.40.5_n1_nb_cf0_ov_acc<-ad_tda_pc_5.40.5_n1_nb_cf0$overall[1]
ad_tda_pc_5.40.5_n1_nb_cf0$byClas1
ad_tda_pc_5.40.5_n1_nb_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n1_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nb_n1_3_fold<-(ad_nb_fit_re - ad_tda_pc_5.40.5_n1_nb_fit_re)
diff_tda_pca_5.40.5_nb_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb_n1_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n1_3_fold_odds.left<-bst_tda_pca_5.40.5_nb.n1_3_fold$probLeft/bst_tda_pca_5.40.5_nb.n1_3_fold$probRight
bst_tda_pca_5.40.5_nb.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb_n1_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n1_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb_n1_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n1_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nb_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n1_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb_n1_3_fold))
#bf_tda_pca_5.40.5_nb.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nb_n1_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nb.n1_test<-(nb_cf_ov_acc - ad_tda_pc_5.40.5_n1_nb_cf0_ov_acc)
diff_tda_pca_5.40.5_nb.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n1_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb.n1_test),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n1_test_odds.left<-bst_tda_pca_5.40.5_nb.n1_test$probLeft/bst_tda_pca_5.40.5_nb.n1_test$probRight
bst_tda_pca_5.40.5_nb.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n1_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb.n1_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n1_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb.n1_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n1_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nb.n1_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n1_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb.n1_test)) #bf_tda_pca_5.40.5_nb.n1_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nb.n1_test))

##Node2

Adult_TDA_PC_5.40.5_n2_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_PC_5.40.5_n2_NbFit0
Adult_TDA_PC_5.40.5_n2_NbFit0$resample
ad_tda_pc_5.40.5_n2_nb_fit_re<-Adult_TDA_PC_5.40.5_n2_NbFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n2_NbFit0)

# Predict outcome using Adult_TDA_PC_5.40.5_n2_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n2_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n2_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n2_nb_cf0
ad_tda_pc_5.40.5_n2_nb_cf0 
ad_tda_pc_5.40.5_n2_nb_cf0$overall
ad_tda_pc_5.40.5_n2_nb_cf0_ov_acc<-ad_tda_pc_5.40.5_n2_nb_cf0$overall[1]
ad_tda_pc_5.40.5_n2_nb_cf0$byClass
ad_tda_pc_5.40.5_n2_nb_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n2_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nb_n2_3_fold<-(ad_nb_fit_re - ad_tda_pc_5.40.5_n2_nb_fit_re)
diff_tda_pca_5.40.5_nb_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb_n2_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n2_3_fold_odds.left<-bst_tda_pca_5.40.5_nb.n2_3_fold$probLeft/bst_tda_pca_5.40.5_nb.n2_3_fold$probRight
bst_tda_pca_5.40.5_nb.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb_n2_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n2_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb_n2_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n2_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nb_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n2_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb_n2_3_fold))
#bf_tda_pca_5.40.5_nb.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nb_n2_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nb.n2_test<-(nb_cf_ov_acc - ad_tda_pc_5.40.5_n2_nb_cf0_ov_acc)
diff_tda_pca_5.40.5_nb.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n2_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb.n2_test),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n2_test_odds.left<-bst_tda_pca_5.40.5_nb.n2_test$probLeft/bst_tda_pca_5.40.5_nb.n2_test$probRight
bst_tda_pca_5.40.5_nb.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n2_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb.n2_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n2_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb.n2_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n2_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nb.n2_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n2_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb.n2_test)) #bf_tda_pca_5.40.5_nb.n2_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nb.n2_test))

##Node3

Adult_TDA_PC_5.40.5_n3_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n3.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_PC_5.40.5_n3_NbFit0
Adult_TDA_PC_5.40.5_n3_NbFit0$resample
ad_tda_pc_5.40.5_n3_nb_fit_re<-Adult_TDA_PC_5.40.5_n3_NbFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n3_NbFit0)

# Predict outcome using Adult_TDA_PC_5.40.5_n3_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n3_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n3_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n3_nb_cf0
ad_tda_pc_5.40.5_n3_nb_cf0 
ad_tda_pc_5.40.5_n3_nb_cf0$overall
ad_tda_pc_5.40.5_n3_nb_cf0_ov_acc<-ad_tda_pc_5.40.5_n3_nb_cf0$overall[1]
ad_tda_pc_5.40.5_n3_nb_cf0$byClass
ad_tda_pc_5.40.5_n3_nb_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n3_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nb_n3_3_fold<-(ad_nb_fit_re - ad_tda_pc_5.40.5_n3_nb_fit_re)
diff_tda_pca_5.40.5_nb_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb_n3_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n3_3_fold_odds.left<-bst_tda_pca_5.40.5_nb.n3_3_fold$probLeft/bst_tda_pca_5.40.5_nb.n3_3_fold$probRight
bst_tda_pca_5.40.5_nb.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb_n3_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n3_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb_n3_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n3_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nb_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n3_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb_n3_3_fold))
#bf_tda_pca_5.40.5_nb.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nb_n3_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nb.n3_test<-(nb_cf_ov_acc - ad_tda_pc_5.40.5_n3_nb_cf0_ov_acc)
diff_tda_pca_5.40.5_nb.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n3_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb.n3_test),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n3_test_odds.left<-bst_tda_pca_5.40.5_nb.n3_test$probLeft/bst_tda_pca_5.40.5_nb.n3_test$probRight
bst_tda_pca_5.40.5_nb.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n2_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb.n2_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n2_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb.n3_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n3_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nb.n3_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n3_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb.n3_test)) #bf_tda_pca_5.40.5_nb.n3_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nb.n3_test))

##Node4

Adult_TDA_PC_5.40.5_n4_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n4.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_PC_5.40.5_n4_NbFit0
Adult_TDA_PC_5.40.5_n4_NbFit0$resample
ad_tda_pc_5.40.5_n4_nb_fit_re<-Adult_TDA_PC_5.40.5_n4_NbFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n4_NbFit0)

# Predict outcome using Adult_TDA_PC_5.40.5_n4_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n4_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n4_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n4_nb_cf0
ad_tda_pc_5.40.5_n4_nb_cf0 
ad_tda_pc_5.40.5_n4_nb_cf0$overall
ad_tda_pc_5.40.5_n4_nb_cf0_ov_acc<-ad_tda_pc_5.40.5_n4_nb_cf0$overall[1]
ad_tda_pc_5.40.5_n4_nb_cf0$byClass
ad_tda_pc_5.40.5_n4_nb_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n4_nb_cf0$byClass[5:7]


###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nb_n4_3_fold<-(ad_nb_fit_re - ad_tda_pc_5.40.5_n4_nb_fit_re)
diff_tda_pca_5.40.5_nb_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb_n4_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n4_3_fold_odds.left<-bst_tda_pca_5.40.5_nb.n4_3_fold$probLeft/bst_tda_pca_5.40.5_nb.n4_3_fold$probRight
bst_tda_pca_5.40.5_nb.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb_n4_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n4_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb_n4_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n4_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nb_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n4_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb_n4_3_fold))
#bf_tda_pca_5.40.5_nb.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nb_n4_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nb.n4_test<-(nb_cf_ov_acc - ad_tda_pc_5.40.5_n4_nb_cf0_ov_acc)
diff_tda_pca_5.40.5_nb.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n4_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb.n4_test),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n4_test_odds.left<-bst_tda_pca_5.40.5_nb.n4_test$probLeft/bst_tda_pca_5.40.5_nb.n4_test$probRight
bst_tda_pca_5.40.5_nb.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n4_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb.n4_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n4_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb.n4_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n4_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nb.n4_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n4_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb.n4_test)) #bf_tda_pca_5.40.5_nb.n4_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nb.n4_test))

##Node5

Adult_TDA_PC_5.40.5_n5_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n5.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_PC_5.40.5_n5_NbFit0
Adult_TDA_PC_5.40.5_n5_NbFit0$resample
ad_tda_pc_5.40.5_n5_nb_fit_re<-Adult_TDA_PC_5.40.5_n5_NbFit0$resample[1]

summary(Adult_TDA_PC_5.40.5_n5_NbFit0)

# Predict outcome using Adult_TDA_PC_5.40.5_n5_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_PC_5.40.5_n5_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_pc_5.40.5_n5_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_pc_5.40.5_n5_nb_cf0
ad_tda_pc_5.40.5_n5_nb_cf0 
ad_tda_pc_5.40.5_n5_nb_cf0$overall
ad_tda_pc_5.40.5_n5_nb_cf0_ov_acc<-ad_tda_pc_5.40.5_n5_nb_cf0$overall[1]
ad_tda_pc_5.40.5_n5_nb_cf0$byClass
ad_tda_pc_5.40.5_n5_nb_cf0_pre_rec_f1<-ad_tda_pc_5.40.5_n5_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_pca_5.40.5_nb_n5_3_fold<-(ad_nb_fit_re - ad_tda_pc_5.40.5_n5_nb_fit_re)
diff_tda_pca_5.40.5_nb_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb_n5_3_fold),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n5_3_fold_odds.left<-bst_tda_pca_5.40.5_nb.n5_3_fold$probLeft/bst_tda_pca_5.40.5_nb.n5_3_fold$probRight
bst_tda_pca_5.40.5_nb.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb_n4_3_fold),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n5_3_fold

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb_n5_3_fold),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n5_3_fold

# Rope Plot
plot(rope(diff_tda_pca_5.40.5_nb_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n5_3_fold = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb_n5_3_fold))
#bf_tda_pca_5.40.5_nb.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_pca_5.40.5_nb_n5_3_fold))


### Test set diff
diff_tda_pca_5.40.5_nb.n5_test<-(nb_cf_ov_acc - ad_tda_pc_5.40.5_n5_nb_cf0_ov_acc)
diff_tda_pca_5.40.5_nb.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_pca_5.40.5_nb.n5_test<-BayesianSignTest(as.matrix(diff_tda_pca_5.40.5_nb.n5_test),-0.01,0.01)
bst_tda_pca_5.40.5_nb.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_pca_5.40.5_nb.n5_test_odds.left<-bst_tda_pca_5.40.5_nb.n5_test$probLeft/bst_tda_pca_5.40.5_nb.n5_test$probRight
bst_tda_pca_5.40.5_nb.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_pca_5.40.5_nb.n5_test<-BayesianSignedRank(as.matrix(diff_tda_pca_5.40.5_nb.n5_test),-0.01,0.01)
bsr_tda_pca_5.40.5_nb.n5_test

# Bayesian Correlated Test

bct_tda_pca_5.40.5_nb.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_pca_5.40.5_nb.n5_test),0.1,-0.01,0.01)
bct_tda_pca_5.40.5_nb.n5_test

# Rope Plot
#plot(rope(diff_tda_pca_5.40.5_nb.n5_test)))

#BayesFactor
#bf_tda_pca_5.40.5_nb.n5_test = ttestBF(x = as.matrix(diff_tda_pca_5.40.5_nb.n5_test)) #bf_tda_pca_5.40.5_nb.n5_test

#t_test
#t.test(as.matrix(diff_tda_pca_5.40.5_nb.n5_test))

##With TDA KDE filter 5 intervals, 50% overlap, 5 bins 
##Node1

Adult_TDA_KDE_5.40.5_n1_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_kde_adult_5.40.5.n1.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n1_NbFit0
Adult_TDA_KDE_5.40.5_n1_NbFit0$resample
ad_tda_kde_5.40.5_n1_nb_fit_re<-Adult_TDA_KDE_5.40.5_n1_NbFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n1_NbFit0)

# Predict outcome using Adult_TDA_KDE_5.40.5_n1_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n1_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n1_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n1_nb_cf0
ad_tda_kde_5.40.5_n1_nb_cf0 
ad_tda_kde_5.40.5_n1_nb_cf0$overall
ad_tda_kde_5.40.5_n1_nb_cf0_ov_acc<-ad_tda_kde_5.40.5_n1_nb_cf0$overall[1]
ad_tda_kde_5.40.5_n1_nb_cf0$byClas1
ad_tda_kde_5.40.5_n1_nb_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n1_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nb_n1_3_fold<-(ad_nb_fit_re - ad_tda_kde_5.40.5_n1_nb_fit_re)
diff_tda_kde_5.40.5_nb_n1_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n1_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb_n1_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n1_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n1_3_fold_odds.left<-bst_tda_kde_5.40.5_nb.n1_3_fold$probLeft/bst_tda_kde_5.40.5_nb.n1_3_fold$probRight
bst_tda_kde_5.40.5_nb.n1_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n1_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb_n1_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n1_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n1_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb_n1_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n1_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nb_n1_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n1_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb_n1_3_fold))
#bf_tda_kde_5.40.5_nb.n1_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nb_n1_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nb.n1_test<-(nb_cf_ov_acc - ad_tda_kde_5.40.5_n1_nb_cf0_ov_acc)
diff_tda_kde_5.40.5_nb.n1_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n1_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb.n1_test),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n1_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n1_test_odds.left<-bst_tda_kde_5.40.5_nb.n1_test$probLeft/bst_tda_kde_5.40.5_nb.n1_test$probRight
bst_tda_kde_5.40.5_nb.n1_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n1_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb.n1_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n1_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n1_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb.n1_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n1_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nb.n1_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n1_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb.n1_test)) #bf_tda_pca_5.40.5_nb.n1_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nb.n1_test))

##Node2

Adult_TDA_KDE_5.40.5_n2_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n2.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n2_NbFit0
Adult_TDA_KDE_5.40.5_n2_NbFit0$resample
ad_tda_kde_5.40.5_n2_nb_fit_re<-Adult_TDA_KDE_5.40.5_n2_NbFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n2_NbFit0)

# Predict outcome using Adult_TDA_KDE_5.40.5_n2_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n2_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n2_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n2_nb_cf0
ad_tda_kde_5.40.5_n2_nb_cf0 
ad_tda_kde_5.40.5_n2_nb_cf0$overall
ad_tda_kde_5.40.5_n2_nb_cf0_ov_acc<-ad_tda_kde_5.40.5_n2_nb_cf0$overall[1]
ad_tda_kde_5.40.5_n2_nb_cf0$byClass
ad_tda_kde_5.40.5_n2_nb_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n2_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nb_n2_3_fold<-(ad_nb_fit_re - ad_tda_kde_5.40.5_n2_nb_fit_re)
diff_tda_kde_5.40.5_nb_n2_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n2_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb_n2_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n2_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n2_3_fold_odds.left<-bst_tda_kde_5.40.5_nb.n2_3_fold$probLeft/bst_tda_kde_5.40.5_nb.n2_3_fold$probRight
bst_tda_kde_5.40.5_nb.n2_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n2_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb_n2_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n2_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n2_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb_n2_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n2_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nb_n2_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n2_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb_n2_3_fold))
#bf_tda_kde_5.40.5_nb.n2_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nb_n2_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nb.n2_test<-(nb_cf_ov_acc - ad_tda_kde_5.40.5_n2_nb_cf0_ov_acc)
diff_tda_kde_5.40.5_nb.n2_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n2_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb.n2_test),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n2_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n2_test_odds.left<-bst_tda_kde_5.40.5_nb.n2_test$probLeft/bst_tda_kde_5.40.5_nb.n2_test$probRight
bst_tda_kde_5.40.5_nb.n2_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n2_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb.n2_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n2_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n2_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb.n2_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n2_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nb.n2_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n2_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb.n2_test)) #bf_tda_kde_5.40.5_nb.n2_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nb.n2_test))

##Node3

Adult_TDA_KDE_5.40.5_n3_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n3.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n3_NbFit0
Adult_TDA_KDE_5.40.5_n3_NbFit0$resample
ad_tda_kde_5.40.5_n3_nb_fit_re<-Adult_TDA_KDE_5.40.5_n3_NbFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n3_NbFit0)

# Predict outcome using Adult_TDA_KDE_5.40.5_n3_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n3_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n3_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n3_nb_cf0
ad_tda_kde_5.40.5_n3_nb_cf0 
ad_tda_kde_5.40.5_n3_nb_cf0$overall
ad_tda_kde_5.40.5_n3_nb_cf0_ov_acc<-ad_tda_kde_5.40.5_n3_nb_cf0$overall[1]
ad_tda_kde_5.40.5_n3_nb_cf0$byClass
ad_tda_kde_5.40.5_n3_nb_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n3_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nb_n3_3_fold<-(ad_nb_fit_re - ad_tda_kde_5.40.5_n3_nb_fit_re)
diff_tda_kde_5.40.5_nb_n3_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n3_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb_n3_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n3_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n3_3_fold_odds.left<-bst_tda_kde_5.40.5_nb.n3_3_fold$probLeft/bst_tda_kde_5.40.5_nb.n3_3_fold$probRight
bst_tda_kde_5.40.5_nb.n3_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n3_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb_n3_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n3_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n3_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb_n3_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n3_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nb_n3_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n3_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb_n3_3_fold))
#bf_tda_kde_5.40.5_nb.n3_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nb_n3_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nb.n3_test<-(nb_cf_ov_acc - ad_tda_kde_5.40.5_n3_nb_cf0_ov_acc)
diff_tda_kde_5.40.5_nb.n3_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n3_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb.n3_test),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n3_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n3_test_odds.left<-bst_tda_kde_5.40.5_nb.n3_test$probLeft/bst_tda_kde_5.40.5_nb.n3_test$probRight
bst_tda_kde_5.40.5_nb.n3_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n3_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb.n3_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n3_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n3_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb.n3_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n3_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nb.n3_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n3_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb.n3_test)) #bf_tda_kde_5.40.5_nb.n3_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nb.n3_test))


##Node4

Adult_TDA_KDE_5.40.5_n4_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n4.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n4_NbFit0
Adult_TDA_KDE_5.40.5_n4_NbFit0$resample
ad_tda_kde_5.40.5_n4_nb_fit_re<-Adult_TDA_KDE_5.40.5_n4_NbFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n4_NbFit0)

# Predict outcome using Adult_TDA_KDE_5.40.5_n4_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n4_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n4_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n4_nb_cf0
ad_tda_kde_5.40.5_n4_nb_cf0 
ad_tda_kde_5.40.5_n4_nb_cf0$overall
ad_tda_kde_5.40.5_n4_nb_cf0_ov_acc<-ad_tda_kde_5.40.5_n4_nb_cf0$overall[1]
ad_tda_kde_5.40.5_n4_nb_cf0$byClass
ad_tda_kde_5.40.5_n4_nb_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n4_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nb_n4_3_fold<-(ad_nb_fit_re - ad_tda_kde_5.40.5_n4_nb_fit_re)
diff_tda_kde_5.40.5_nb_n4_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n4_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb_n4_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n4_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n4_3_fold_odds.left<-bst_tda_kde_5.40.5_nb.n4_3_fold$probLeft/bst_tda_kde_5.40.5_nb.n4_3_fold$probRight
bst_tda_kde_5.40.5_nb.n4_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n4_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb_n4_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n4_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n4_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb_n4_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n4_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nb_n4_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n4_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb_n4_3_fold))
#bf_tda_kde_5.40.5_nb.n4_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nb_n4_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nb.n4_test<-(nb_cf_ov_acc - ad_tda_kde_5.40.5_n4_nb_cf0_ov_acc)
diff_tda_kde_5.40.5_nb.n4_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n4_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb.n4_test),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n4_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n4_test_odds.left<-bst_tda_kde_5.40.5_nb.n4_test$probLeft/bst_tda_kde_5.40.5_nb.n4_test$probRight
bst_tda_kde_5.40.5_nb.n4_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n4_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb.n4_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n4_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n4_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb.n4_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n4_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nb.n4_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n4_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb.n4_test)) #bf_tda_kde_5.40.5_nb.n4_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nb.n4_test))

##Node5

Adult_TDA_KDE_5.40.5_n5_NbFit0 <- train(as.factor(adult_df1) ~ ., data = tda.m_adult_5.40.5.n5.vec, 
                method = 'nb', 
                trControl = fitControl,
                metric='Accuracy')

Adult_TDA_KDE_5.40.5_n5_NbFit0
Adult_TDA_KDE_5.40.5_n5_NbFit0$resample
ad_tda_kde_5.40.5_n5_nb_fit_re<-Adult_TDA_KDE_5.40.5_n5_NbFit0$resample[1]

summary(Adult_TDA_KDE_5.40.5_n5_NbFit0)

# Predict outcome using Adult_TDA_KDE_5.40.5_n5_NbFit0 from training data based on testing data
pred0 <- predict(Adult_TDA_KDE_5.40.5_n5_NbFit0, newdata= adult.one_hot_df4Test)

# Create confusion matrix to assess model fit/performance on test data
ad_tda_kde_5.40.5_n5_nb_cf0<-confusionMatrix(data=pred0, as.factor(adult.one_hot_df4Test$adult_df1))
ad_tda_kde_5.40.5_n5_nb_cf0
ad_tda_kde_5.40.5_n5_nb_cf0 
ad_tda_kde_5.40.5_n5_nb_cf0$overall
ad_tda_kde_5.40.5_n5_nb_cf0_ov_acc<-ad_tda_kde_5.40.5_n5_nb_cf0$overall[1]
ad_tda_kde_5.40.5_n5_nb_cf0$byClass
ad_tda_kde_5.40.5_n5_nb_cf0_pre_rec_f1<-ad_tda_kde_5.40.5_n5_nb_cf0$byClass[5:7]

###### Conduct initial Bayesian tests of non-tda-assisted RF vs. tda-assisted RF classifiers

### 3-fold diff

diff_tda_kde_5.40.5_nb_n5_3_fold<-(ad_nb_fit_re - ad_tda_kde_5.40.5_n5_nb_fit_re)
diff_tda_kde_5.40.5_nb_n5_3_fold

## Bayesian Tests 3-fold diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n5_3_fold<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb_n5_3_fold),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n5_3_fold

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n5_3_fold_odds.left<-bst_tda_kde_5.40.5_nb.n5_3_fold$probLeft/bst_tda_kde_5.40.5_nb.n5_3_fold$probRight
bst_tda_kde_5.40.5_nb.n5_3_fold_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n5_3_fold<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb_n5_3_fold),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n5_3_fold

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n5_3_fold<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb_n5_3_fold),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n5_3_fold

# Rope Plot
plot(rope(diff_tda_kde_5.40.5_nb_n5_3_fold,c(-0.01,0.01)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n5_3_fold = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb_n5_3_fold))
#bf_tda_kde_5.40.5_nb.n5_3_fold

#t_test
t.test(as.matrix(diff_tda_kde_5.40.5_nb_n5_3_fold))


### Test set diff
diff_tda_kde_5.40.5_nb.n5_test<-(nb_cf_ov_acc - ad_tda_kde_5.40.5_n5_nb_cf0_ov_acc)
diff_tda_kde_5.40.5_nb.n5_test


## Bayesian Tests Test set diff

# Bayesian Sign Test

bst_tda_kde_5.40.5_nb.n5_test<-BayesianSignTest(as.matrix(diff_tda_kde_5.40.5_nb.n5_test),-0.01,0.01)
bst_tda_kde_5.40.5_nb.n5_test

# Odds Left Bayesian Sign Test 

bst_tda_kde_5.40.5_nb.n5_test_odds.left<-bst_tda_kde_5.40.5_nb.n5_test$probLeft/bst_tda_kde_5.40.5_nb.n5_test$probRight
bst_tda_kde_5.40.5_nb.n5_test_odds.left

# Bayesian Signed Rank Test

bsr_tda_kde_5.40.5_nb.n5_test<-BayesianSignedRank(as.matrix(diff_tda_kde_5.40.5_nb.n5_test),-0.01,0.01)
bsr_tda_kde_5.40.5_nb.n5_test

# Bayesian Correlated Test

bct_tda_kde_5.40.5_nb.n5_test<-correlatedBayesianTtest(as.matrix(diff_tda_kde_5.40.5_nb.n5_test),0.1,-0.01,0.01)
bct_tda_kde_5.40.5_nb.n5_test

# Rope Plot
#plot(rope(diff_tda_kde_5.40.5_nb.n5_test)))

#BayesFactor
#bf_tda_kde_5.40.5_nb.n5_test = ttestBF(x = as.matrix(diff_tda_kde_5.40.5_nb.n5_test)) #bf_tda_kde_5.40.5_nb.n5_test

#t_test
#t.test(as.matrix(diff_tda_kde_5.40.5_nb.n5_test))

```

